package arm.node;

@:keep class Spawn_Beams_Control_v3 extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _DespawnBeams = new armory.logicnode.DespawnBeams(this);
		var _Branch = new armory.logicnode.BranchNode(this);
		var _Timer = new armory.logicnode.TimerNode(this);
		var _OnUpdate = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate.property0 = "Update";
		_OnUpdate.addOutputs([_Timer]);
		_Timer.addInput(_OnUpdate, 0);
		_Timer.addInput(new armory.logicnode.NullNode(this), 0);
		_Timer.addInput(new armory.logicnode.NullNode(this), 0);
		var _GetProperty_006 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_003 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_003.addOutputs([_GetProperty_006]);
		_GetProperty_006.addInput(_GlobalObject_003, 0);
		_GetProperty_006.addInput(new armory.logicnode.StringNode(this, "UpdateTime"), 0);
		_GetProperty_006.addOutputs([_Timer]);
		_GetProperty_006.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Timer.addInput(_GetProperty_006, 0);
		_Timer.addInput(new armory.logicnode.IntegerNode(this, 1), 0);
		_Timer.addOutputs([_Branch]);
		_Timer.addOutputs([new armory.logicnode.NullNode(this)]);
		_Timer.addOutputs([new armory.logicnode.BooleanNode(this, false)]);
		_Timer.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_Timer.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_Timer.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Timer.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Branch.addInput(_Timer, 0);
		var _GetProperty = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_001 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_001.addOutputs([_GetProperty]);
		_GetProperty.addInput(_GlobalObject_001, 0);
		_GetProperty.addInput(new armory.logicnode.StringNode(this, "Laser_on"), 0);
		_GetProperty.addOutputs([_Branch]);
		_GetProperty.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Branch.addInput(_GetProperty, 0);
		var _CalculateBeamPositions_002 = new armory.logicnode.CalculateBeamPositions(this);
		_CalculateBeamPositions_002.addInput(_Branch, 0);
		var _GetProperty_039 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_043 = new armory.logicnode.GlobalObjectNode(this);
		var _GetProperty_041 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_041.addInput(_GlobalObject_043, 0);
		_GetProperty_041.addInput(new armory.logicnode.StringNode(this, "Array_Pump_Beam_sources"), 0);
		_GetProperty_041.addOutputs([_CalculateBeamPositions_002]);
		_GetProperty_041.addOutputs([new armory.logicnode.StringNode(this, "")]);
		var _GetProperty_040 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_040.addInput(_GlobalObject_043, 0);
		_GetProperty_040.addInput(new armory.logicnode.StringNode(this, "Object_Pump_Laser"), 0);
		_GetProperty_040.addOutputs([_CalculateBeamPositions_002]);
		_GetProperty_040.addOutputs([new armory.logicnode.StringNode(this, "")]);
		var _GetProperty_042 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_042.addInput(_GlobalObject_043, 0);
		_GetProperty_042.addInput(new armory.logicnode.StringNode(this, "Array_Pump_Beam_objects"), 0);
		var _SpawnBeams_001 = new armory.logicnode.SpawnBeams(this);
		_SpawnBeams_001.addInput(_CalculateBeamPositions_002, 0);
		_SpawnBeams_001.addInput(_CalculateBeamPositions_002, 1);
		_SpawnBeams_001.addInput(_CalculateBeamPositions_002, 2);
		_SpawnBeams_001.addInput(_CalculateBeamPositions_002, 3);
		_SpawnBeams_001.addInput(_GetProperty_042, 0);
		_SpawnBeams_001.addInput(new armory.logicnode.StringNode(this, "Beam"), 0);
		_SpawnBeams_001.addInput(new armory.logicnode.StringNode(this, "arr_sub_objects"), 0);
		_SpawnBeams_001.addInput(new armory.logicnode.StringNode(this, "String_Beam_Ray_Traits"), 0);
		_SpawnBeams_001.addInput(new armory.logicnode.StringNode(this, "GetChildProperties"), 0);
		_SpawnBeams_001.addInput(_CalculateBeamPositions_002, 4);
		_SpawnBeams_001.addInput(new armory.logicnode.FloatNode(this, 0.25), 0);
		var _SpawnandDespawnPolarizationArrows_001 = new armory.logicnode.SpawnDespawnPol(this);
		_SpawnandDespawnPolarizationArrows_001.addInput(_SpawnBeams_001, 0);
		_SpawnandDespawnPolarizationArrows_001.addInput(_CalculateBeamPositions_002, 1);
		_SpawnandDespawnPolarizationArrows_001.addInput(_CalculateBeamPositions_002, 2);
		_SpawnandDespawnPolarizationArrows_001.addInput(_SpawnBeams_001, 1);
		var _GetProperty_008 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_045 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_045.addOutputs([_GetProperty_008]);
		_GetProperty_008.addInput(_GlobalObject_045, 0);
		_GetProperty_008.addInput(new armory.logicnode.StringNode(this, "all_pol_Arrows"), 0);
		_GetProperty_008.addOutputs([_SpawnandDespawnPolarizationArrows_001]);
		_GetProperty_008.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_SpawnandDespawnPolarizationArrows_001.addInput(_GetProperty_008, 0);
		_SpawnandDespawnPolarizationArrows_001.addInput(new armory.logicnode.StringNode(this, "pol_arrows"), 0);
		_SpawnandDespawnPolarizationArrows_001.addInput(new armory.logicnode.StringNode(this, "arr_sub_objects"), 0);
		_SpawnandDespawnPolarizationArrows_001.addInput(new armory.logicnode.FloatNode(this, 0.5), 0);
		_SpawnandDespawnPolarizationArrows_001.addInput(new armory.logicnode.FloatNode(this, 0.30000001192092896), 0);
		_SpawnandDespawnPolarizationArrows_001.addInput(new armory.logicnode.FloatNode(this, 2.049999952316284), 0);
		_SpawnandDespawnPolarizationArrows_001.addInput(new armory.logicnode.IntegerNode(this, 30), 0);
		var _GetProperty_007 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_044 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_044.addOutputs([_GetProperty_007]);
		_GetProperty_007.addInput(_GlobalObject_044, 0);
		_GetProperty_007.addInput(new armory.logicnode.StringNode(this, "Pol_on"), 0);
		_GetProperty_007.addOutputs([_SpawnandDespawnPolarizationArrows_001]);
		_GetProperty_007.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_SpawnandDespawnPolarizationArrows_001.addInput(_GetProperty_007, 0);
		_SpawnandDespawnPolarizationArrows_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Print_006 = new armory.logicnode.PrintNode(this);
		_Print_006.addInput(_SpawnBeams_001, 0);
		_Print_006.addInput(new armory.logicnode.StringNode(this, "test"), 0);
		_Print_006.addOutputs([new armory.logicnode.NullNode(this)]);
		_SpawnBeams_001.addOutputs([_SpawnandDespawnPolarizationArrows_001, _Print_006]);
		var _ArrayLength_001 = new armory.logicnode.ArrayLengthNode(this);
		_ArrayLength_001.addInput(_SpawnBeams_001, 1);
		var _Print_002 = new armory.logicnode.PrintNode(this);
		var _OnKeyboard_002 = new armory.logicnode.OnKeyboardNode(this);
		_OnKeyboard_002.property0 = "Started";
		_OnKeyboard_002.property1 = "p";
		_OnKeyboard_002.addOutputs([_Print_002]);
		_Print_002.addInput(_OnKeyboard_002, 0);
		_Print_002.addInput(_ArrayLength_001, 0);
		var _Print_003 = new armory.logicnode.PrintNode(this);
		_Print_003.addInput(_Print_002, 0);
		var _ArrayLength_002 = new armory.logicnode.ArrayLengthNode(this);
		_ArrayLength_002.addInput(_CalculateBeamPositions_002, 1);
		_ArrayLength_002.addOutputs([_Print_003]);
		_Print_003.addInput(_ArrayLength_002, 0);
		_Print_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_Print_002.addOutputs([_Print_003]);
		_ArrayLength_001.addOutputs([_Print_002]);
		_SpawnBeams_001.addOutputs([_SpawnandDespawnPolarizationArrows_001, _ArrayLength_001]);
		_GetProperty_042.addOutputs([_DespawnBeams, _SpawnBeams_001]);
		_GetProperty_042.addOutputs([new armory.logicnode.StringNode(this, "")]);
		var _GetProperty_043 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_043.addInput(_GlobalObject_043, 0);
		_GetProperty_043.addInput(new armory.logicnode.StringNode(this, "Array_Pump_Beam_directions"), 0);
		_GetProperty_043.addOutputs([_CalculateBeamPositions_002]);
		_GetProperty_043.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_GlobalObject_043.addOutputs([_GetProperty_039, _GetProperty_041, _GetProperty_040, _GetProperty_042, _GetProperty_043]);
		_GetProperty_039.addInput(_GlobalObject_043, 0);
		_GetProperty_039.addInput(new armory.logicnode.StringNode(this, "Array_Pump_Beam_positions"), 0);
		_GetProperty_039.addOutputs([_CalculateBeamPositions_002]);
		_GetProperty_039.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_CalculateBeamPositions_002.addInput(_GetProperty_039, 0);
		_CalculateBeamPositions_002.addInput(_GetProperty_043, 0);
		_CalculateBeamPositions_002.addInput(_GetProperty_041, 0);
		_CalculateBeamPositions_002.addInput(_GetProperty_040, 0);
		_CalculateBeamPositions_002.addInput(new armory.logicnode.StringNode(this, "String_Beam_Ray_Traits"), 0);
		_CalculateBeamPositions_002.addInput(new armory.logicnode.StringNode(this, "Get_Beam_Direction"), 0);
		_CalculateBeamPositions_002.addInput(new armory.logicnode.IntegerNode(this, 2), 0);
		var _GetProperty_005 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_002 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_002.addOutputs([_GetProperty_005]);
		_GetProperty_005.addInput(_GlobalObject_002, 0);
		_GetProperty_005.addInput(new armory.logicnode.StringNode(this, "BeamNumber"), 0);
		_GetProperty_005.addOutputs([_CalculateBeamPositions_002]);
		_GetProperty_005.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_CalculateBeamPositions_002.addInput(_GetProperty_005, 0);
		var _Print_005 = new armory.logicnode.PrintNode(this);
		_Print_005.addInput(_CalculateBeamPositions_002, 0);
		var _ArrayLength_003 = new armory.logicnode.ArrayLengthNode(this);
		_ArrayLength_003.addInput(_CalculateBeamPositions_002, 1);
		_ArrayLength_003.addOutputs([_Print_005]);
		_Print_005.addInput(_ArrayLength_003, 0);
		_Print_005.addOutputs([new armory.logicnode.NullNode(this)]);
		_CalculateBeamPositions_002.addOutputs([_SpawnBeams_001, _Print_005]);
		_CalculateBeamPositions_002.addOutputs([_SpawnBeams_001, _SpawnandDespawnPolarizationArrows_001, _ArrayLength_002, _ArrayLength_003]);
		_CalculateBeamPositions_002.addOutputs([_SpawnBeams_001, _SpawnandDespawnPolarizationArrows_001]);
		_CalculateBeamPositions_002.addOutputs([_SpawnBeams_001]);
		_CalculateBeamPositions_002.addOutputs([_SpawnBeams_001]);
		_Branch.addOutputs([_CalculateBeamPositions_002]);
		_Branch.addOutputs([_DespawnBeams]);
		_DespawnBeams.addInput(_Branch, 1);
		_DespawnBeams.addInput(_GetProperty_042, 0);
		_DespawnBeams.addInput(new armory.logicnode.StringNode(this, "arr_sub_objects"), 0);
		_DespawnBeams.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Print_001 = new armory.logicnode.PrintNode(this);
		var _ArrayLoop = new armory.logicnode.ArrayLoopNode(this);
		var _OnKeyboard_001 = new armory.logicnode.OnKeyboardNode(this);
		_OnKeyboard_001.property0 = "Started";
		_OnKeyboard_001.property1 = "l";
		_OnKeyboard_001.addOutputs([_ArrayLoop]);
		_ArrayLoop.addInput(_OnKeyboard_001, 0);
		var _GetProperty_010 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_047 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_047.addOutputs([_GetProperty_010]);
		_GetProperty_010.addInput(_GlobalObject_047, 0);
		_GetProperty_010.addInput(new armory.logicnode.StringNode(this, "all_pol_Arrows"), 0);
		_GetProperty_010.addOutputs([_ArrayLoop]);
		_GetProperty_010.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_ArrayLoop.addInput(_GetProperty_010, 0);
		_ArrayLoop.addOutputs([_Print_001]);
		var _GetLocation = new armory.logicnode.GetLocationNode(this);
		_GetLocation.addInput(_ArrayLoop, 1);
		_GetLocation.addOutputs([_Print_001]);
		_ArrayLoop.addOutputs([_GetLocation]);
		_ArrayLoop.addOutputs([new armory.logicnode.NullNode(this)]);
		_Print_001.addInput(_ArrayLoop, 0);
		_Print_001.addInput(_GetLocation, 0);
		_Print_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Print = new armory.logicnode.PrintNode(this);
		var _OnKeyboard = new armory.logicnode.OnKeyboardNode(this);
		_OnKeyboard.property0 = "Started";
		_OnKeyboard.property1 = "space";
		_OnKeyboard.addOutputs([_Print]);
		_Print.addInput(_OnKeyboard, 0);
		var _ArrayLength = new armory.logicnode.ArrayLengthNode(this);
		var _GetProperty_009 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_046 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_046.addOutputs([_GetProperty_009]);
		_GetProperty_009.addInput(_GlobalObject_046, 0);
		_GetProperty_009.addInput(new armory.logicnode.StringNode(this, "all_pol_Arrows"), 0);
		_GetProperty_009.addOutputs([_ArrayLength]);
		_GetProperty_009.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_ArrayLength.addInput(_GetProperty_009, 0);
		_ArrayLength.addOutputs([_Print]);
		_Print.addInput(_ArrayLength, 0);
		_Print.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_019 = new armory.logicnode.SetPropertyNode(this);
		var _OnInit = new armory.logicnode.OnInitNode(this);
		var _SetProperty_016 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_016.addInput(_OnInit, 0);
		var _GlobalObject = new armory.logicnode.GlobalObjectNode(this);
		var _SetProperty_017 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_017.addInput(_OnInit, 0);
		_SetProperty_017.addInput(_GlobalObject, 0);
		_SetProperty_017.addInput(new armory.logicnode.StringNode(this, "Array_Pump_Beam_objects"), 0);
		var _Array_Object_ = new armory.logicnode.ArrayObjectNode(this);
		_Array_Object_.addOutputs([_SetProperty_017]);
		_Array_Object_.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_SetProperty_017.addInput(_Array_Object_, 0);
		var _SetProperty_022 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_022.addInput(_SetProperty_017, 0);
		var _GlobalObject_010 = new armory.logicnode.GlobalObjectNode(this);
		var _SetProperty_023 = new armory.logicnode.SetPropertyNode(this);
		var _SetProperty_020 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_020.addInput(_OnInit, 0);
		_SetProperty_020.addInput(_GlobalObject, 0);
		_SetProperty_020.addInput(new armory.logicnode.StringNode(this, "Array_Pump_Beam_positions"), 0);
		var _Array = new armory.logicnode.ArrayNode(this);
		_Array.addOutputs([_SetProperty_020]);
		_Array.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_SetProperty_020.addInput(_Array, 0);
		_SetProperty_020.addOutputs([_SetProperty_023]);
		_SetProperty_023.addInput(_SetProperty_020, 0);
		_SetProperty_023.addInput(_GlobalObject_010, 0);
		_SetProperty_023.addInput(new armory.logicnode.StringNode(this, "Array_Beam_Arrays_positions"), 0);
		var _Array_003 = new armory.logicnode.ArrayNode(this);
		var _GetProperty_002 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_002.addInput(_GlobalObject_010, 0);
		_GetProperty_002.addInput(new armory.logicnode.StringNode(this, "Array_Pump_Beam_positions"), 0);
		_GetProperty_002.addOutputs([_Array_003]);
		_GetProperty_002.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Array_003.addInput(_GetProperty_002, 0);
		_Array_003.addOutputs([_SetProperty_023]);
		_Array_003.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_SetProperty_023.addInput(_Array_003, 0);
		_SetProperty_023.addOutputs([new armory.logicnode.NullNode(this)]);
		var _GetProperty_001 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_001.addInput(_GlobalObject_010, 0);
		_GetProperty_001.addInput(new armory.logicnode.StringNode(this, "Array_Pump_Beam_objects"), 0);
		var _Array_002 = new armory.logicnode.ArrayNode(this);
		_Array_002.addInput(_GetProperty_001, 0);
		_Array_002.addOutputs([_SetProperty_022]);
		_Array_002.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_GetProperty_001.addOutputs([_Array_002]);
		_GetProperty_001.addOutputs([new armory.logicnode.StringNode(this, "")]);
		var _GetProperty_003 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_003.addInput(_GlobalObject_010, 0);
		_GetProperty_003.addInput(new armory.logicnode.StringNode(this, "Array_Pump_Beam_objects"), 0);
		var _Array_004 = new armory.logicnode.ArrayNode(this);
		_Array_004.addInput(_GetProperty_003, 0);
		var _SetProperty_025 = new armory.logicnode.SetPropertyNode(this);
		var _SetProperty_024 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_024.addInput(_OnInit, 0);
		_SetProperty_024.addInput(_GlobalObject, 0);
		_SetProperty_024.addInput(new armory.logicnode.StringNode(this, "Array_Pump_Beam_sources"), 0);
		var _Array_Object__001 = new armory.logicnode.ArrayObjectNode(this);
		_Array_Object__001.addOutputs([_SetProperty_024]);
		_Array_Object__001.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_SetProperty_024.addInput(_Array_Object__001, 0);
		_SetProperty_024.addOutputs([_SetProperty_025]);
		_SetProperty_025.addInput(_SetProperty_024, 0);
		_SetProperty_025.addInput(_GlobalObject_010, 0);
		_SetProperty_025.addInput(new armory.logicnode.StringNode(this, "Array_Beam_Arrays_sources"), 0);
		_SetProperty_025.addInput(_Array_004, 0);
		_SetProperty_025.addOutputs([new armory.logicnode.NullNode(this)]);
		_Array_004.addOutputs([_SetProperty_025]);
		_Array_004.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_GetProperty_003.addOutputs([_Array_004]);
		_GetProperty_003.addOutputs([new armory.logicnode.StringNode(this, "")]);
		var _SetProperty_026 = new armory.logicnode.SetPropertyNode(this);
		var _SetProperty_021 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_021.addInput(_OnInit, 0);
		_SetProperty_021.addInput(_GlobalObject, 0);
		_SetProperty_021.addInput(new armory.logicnode.StringNode(this, "Array_Pump_Beam_directions"), 0);
		var _Array_001 = new armory.logicnode.ArrayNode(this);
		_Array_001.addOutputs([_SetProperty_021]);
		_Array_001.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_SetProperty_021.addInput(_Array_001, 0);
		_SetProperty_021.addOutputs([_SetProperty_026]);
		_SetProperty_026.addInput(_SetProperty_021, 0);
		_SetProperty_026.addInput(_GlobalObject_010, 0);
		_SetProperty_026.addInput(new armory.logicnode.StringNode(this, "Array_Beam_Arrays_directions"), 0);
		var _Array_005 = new armory.logicnode.ArrayNode(this);
		var _GetProperty_004 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_004.addInput(_GlobalObject_010, 0);
		_GetProperty_004.addInput(new armory.logicnode.StringNode(this, "Array_Pump_Beam_positions"), 0);
		_GetProperty_004.addOutputs([_Array_005]);
		_GetProperty_004.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Array_005.addInput(_GetProperty_004, 0);
		_Array_005.addOutputs([_SetProperty_026]);
		_Array_005.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_SetProperty_026.addInput(_Array_005, 0);
		_SetProperty_026.addOutputs([new armory.logicnode.NullNode(this)]);
		_GlobalObject_010.addOutputs([_SetProperty_022, _SetProperty_023, _GetProperty_001, _GetProperty_002, _GetProperty_003, _SetProperty_025, _SetProperty_026, _GetProperty_004]);
		_SetProperty_022.addInput(_GlobalObject_010, 0);
		_SetProperty_022.addInput(new armory.logicnode.StringNode(this, "Array_Beam_Arrays_objects"), 0);
		_SetProperty_022.addInput(_Array_002, 0);
		_SetProperty_022.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetProperty_017.addOutputs([_SetProperty_022]);
		var _SetProperty = new armory.logicnode.SetPropertyNode(this);
		_SetProperty.addInput(_OnInit, 0);
		_SetProperty.addInput(_GlobalObject, 0);
		_SetProperty.addInput(new armory.logicnode.StringNode(this, "BeamNumber"), 0);
		var _Integer = new armory.logicnode.IntegerNode(this);
		_Integer.addInput(new armory.logicnode.IntegerNode(this, 25), 0);
		_Integer.addOutputs([_SetProperty]);
		_SetProperty.addInput(_Integer, 0);
		_SetProperty.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_001 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_001.addInput(_OnInit, 0);
		_SetProperty_001.addInput(_GlobalObject, 0);
		_SetProperty_001.addInput(new armory.logicnode.StringNode(this, "UpdateTime"), 0);
		var _Float = new armory.logicnode.FloatNode(this);
		_Float.addInput(new armory.logicnode.FloatNode(this, 0.02500000037252903), 0);
		_Float.addOutputs([_SetProperty_001]);
		_SetProperty_001.addInput(_Float, 0);
		_SetProperty_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_027 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_027.addInput(_OnInit, 0);
		_SetProperty_027.addInput(_GlobalObject, 0);
		_SetProperty_027.addInput(new armory.logicnode.StringNode(this, "all_pol_Arrows"), 0);
		var _Array_Object__002 = new armory.logicnode.ArrayObjectNode(this);
		_Array_Object__002.addOutputs([_SetProperty_027]);
		_Array_Object__002.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_SetProperty_027.addInput(_Array_Object__002, 0);
		_SetProperty_027.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_002 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_002.addInput(_OnInit, 0);
		_SetProperty_002.addInput(_GlobalObject, 0);
		_SetProperty_002.addInput(new armory.logicnode.StringNode(this, "Pol_on"), 0);
		var _Boolean_001 = new armory.logicnode.BooleanNode(this);
		_Boolean_001.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_Boolean_001.addOutputs([_SetProperty_019, _SetProperty_002]);
		_SetProperty_002.addInput(_Boolean_001, 0);
		_SetProperty_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_GlobalObject.addOutputs([_SetProperty_016, _SetProperty_017, _SetProperty_019, _SetProperty_020, _SetProperty_024, _SetProperty_021, _SetProperty, _SetProperty_001, _SetProperty_027, _SetProperty_002]);
		_SetProperty_016.addInput(_GlobalObject, 0);
		_SetProperty_016.addInput(new armory.logicnode.StringNode(this, "Object_Pump_Laser"), 0);
		var _GetObject = new armory.logicnode.GetObjectNode(this);
		_GetObject.addInput(new armory.logicnode.StringNode(this, "LDM56"), 0);
		_GetObject.addOutputs([_SetProperty_016]);
		_SetProperty_016.addInput(_GetObject, 0);
		_SetProperty_016.addOutputs([new armory.logicnode.NullNode(this)]);
		_OnInit.addOutputs([_SetProperty_016, _SetProperty_017, _SetProperty_019, _SetProperty_020, _SetProperty_024, _SetProperty_021, _SetProperty, _SetProperty_001, _SetProperty_027, _SetProperty_002]);
		_SetProperty_019.addInput(_OnInit, 0);
		_SetProperty_019.addInput(_GlobalObject, 0);
		_SetProperty_019.addInput(new armory.logicnode.StringNode(this, "Laser_on"), 0);
		_SetProperty_019.addInput(_Boolean_001, 0);
		_SetProperty_019.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Print_004 = new armory.logicnode.PrintNode(this);
		var _OnKeyboard_003 = new armory.logicnode.OnKeyboardNode(this);
		_OnKeyboard_003.property0 = "Started";
		_OnKeyboard_003.property1 = "a";
		_OnKeyboard_003.addOutputs([_Print_004]);
		_Print_004.addInput(_OnKeyboard_003, 0);
		_Print_004.addInput(new armory.logicnode.StringNode(this, "test"), 0);
		_Print_004.addOutputs([new armory.logicnode.NullNode(this)]);
		var _OnEvent = new armory.logicnode.OnEventNode(this);
		_OnEvent.property0 = "Calc_Beams";
		_OnEvent.addOutputs([new armory.logicnode.NullNode(this)]);
	}
}