// Auto-generated
let project = new Project('RSP1D_Rotationmount');

project.addSources('Sources');
project.addLibrary("C:/ArmorySDK/armory");
project.addLibrary("C:/ArmorySDK/iron");
project.addLibrary("C:/ArmorySDK/lib/haxebullet");
project.addAssets("C:/ArmorySDK/lib/haxebullet/ammo/ammo.js", { notinlist: true });
project.addParameter('arm.Color_trait');
project.addParameter("--macro keep('arm.Color_trait')");
project.addParameter('arm.UPH2_Base');
project.addParameter("--macro keep('arm.UPH2_Base')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addParameter('arm.Spawner_UPH2');
project.addParameter("--macro keep('arm.Spawner_UPH2')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('arm.Beam_Control_v6');
project.addParameter("--macro keep('arm.Beam_Control_v6')");
project.addParameter('arm.Spawner_RSP1D');
project.addParameter("--macro keep('arm.Spawner_RSP1D')");
project.addParameter('arm.ResumeTraitSelector');
project.addParameter("--macro keep('arm.ResumeTraitSelector')");
project.addParameter('arm.NewUI');
project.addParameter("--macro keep('arm.NewUI')");
project.addParameter('arm.node.Kamera_Bewegung');
project.addParameter("--macro keep('arm.node.Kamera_Bewegung')");
project.addParameter('armory.trait.internal.Bridge');
project.addParameter("--macro keep('armory.trait.internal.Bridge')");
project.addParameter('arm.PumpLaser');
project.addParameter("--macro keep('arm.PumpLaser')");
project.addParameter('arm.Waveplate_half_v2');
project.addParameter("--macro keep('arm.Waveplate_half_v2')");
project.addParameter('arm.RSP1D_Base');
project.addParameter("--macro keep('arm.RSP1D_Base')");
project.addParameter('arm.LDM56_Base');
project.addParameter("--macro keep('arm.LDM56_Base')");
project.addParameter('arm.node.Genral_Object_properties_blocking');
project.addParameter("--macro keep('arm.node.Genral_Object_properties_blocking')");
project.addParameter('armory.trait.internal.DebugConsole');
project.addParameter("--macro keep('armory.trait.internal.DebugConsole')");
project.addShaders("build_RSP1D_Rotationmount/compiled/Shaders/*.glsl", { noembed: false});
project.addAssets("build_RSP1D_Rotationmount/compiled/Assets/**", { notinlist: true });
project.addAssets("build_RSP1D_Rotationmount/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("../../MiReQu_data/Texturen/General/Platte_Occlusion_Diffusion.png", { notinlist: true });
project.addAssets("../../MiReQu_data/Texturen/General/Schraube_Occlusion_Diffusion.png", { notinlist: true });
project.addAssets("../../MiReQu_data/Texturen/LDM_56_Laser/BA2_Occlusion_Diffusion.png", { notinlist: true });
project.addAssets("../../MiReQu_data/Texturen/LDM_56_Laser/LDM_56_Diffusion_Occlusion_collage.png", { notinlist: true });
project.addAssets("../../MiReQu_data/Texturen/Post_and_holder/PH15_Diffusion_Occlusion.png", { notinlist: true });
project.addAssets("../../MiReQu_data/Texturen/Post_and_holder/TR2_Diffusion_Occlusion.png", { notinlist: true });
project.addAssets("../../MiReQu_data/Texturen/Post_and_holder/UPH2_Base_Occlusion_Diffusion.png", { notinlist: true });
project.addAssets("../../MiReQu_data/Texturen/RSP1D_Rotationmount/RSP1D_Diffusion_Occlusion.png", { notinlist: true });
project.addShaders("C:/ArmorySDK/armory/Shaders/debug_draw/**");
project.addLibrary("C:/ArmorySDK/lib/zui");
project.addAssets("C:/ArmorySDK/armory/Assets/font_default.ttf", { notinlist: false });
project.addDefine('arm_legacy');
project.addDefine('rp_renderer=Forward');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_cascade=1024');
project.addDefine('rp_shadowmap_cube=256');
project.addDefine('rp_background=Clear');
project.addDefine('arm_audio');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_soundcompress');
project.addDefine('arm_debug');
project.addDefine('arm_ui');
project.addDefine('arm_skin');
project.addDefine('arm_particles');
project.addDefine('arm_resizable');


resolve(project);
