package arm.node;

@:keep class Movement_Rotation_central extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		name = "Movement_Rotation_central";
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _SendGlobalEvent = new armory.logicnode.SendGlobalEventNode(this);
		var _Merge = new armory.logicnode.MergeNode(this);
		var _TranslateObject_002 = new armory.logicnode.TranslateObjectNode(this);
		var _Gate = new armory.logicnode.GateNode(this);
		_Gate.property0 = "And";
		_Gate.property1 = 9.999999747378752e-05;
		var _OnMouse = new armory.logicnode.OnMouseNode(this);
		_OnMouse.property0 = "Down";
		_OnMouse.property1 = "left";
		_OnMouse.addOutputs([_Gate]);
		_Gate.addInput(_OnMouse, 0);
		var _GetProperty_005 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_007 = new armory.logicnode.GlobalObjectNode(this);
		var _GetProperty_008 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_008.addInput(_GlobalObject_007, 0);
		_GetProperty_008.addInput(new armory.logicnode.StringNode(this, "move_permission"), 0);
		_GetProperty_008.addOutputs([_Gate]);
		_GetProperty_008.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_GlobalObject_007.addOutputs([_GetProperty_005, _GetProperty_008]);
		_GetProperty_005.addInput(_GlobalObject_007, 0);
		_GetProperty_005.addInput(new armory.logicnode.StringNode(this, "Object_movable"), 0);
		_GetProperty_005.addOutputs([_Gate]);
		_GetProperty_005.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Gate.addInput(_GetProperty_005, 0);
		_Gate.addInput(_GetProperty_008, 0);
		_Gate.addOutputs([_TranslateObject_002]);
		var _TranslateObject = new armory.logicnode.TranslateObjectNode(this);
		_TranslateObject.addInput(_Gate, 1);
		var _ActiveCamera = new armory.logicnode.ActiveCameraNode(this);
		var _GetTransform = new armory.logicnode.GetTransformNode(this);
		_GetTransform.addInput(_ActiveCamera, 0);
		var _VectorFromTransform = new armory.logicnode.VectorFromTransformNode(this);
		_VectorFromTransform.property0 = "Right";
		_VectorFromTransform.addInput(_GetTransform, 0);
		var _VectorAngles2DXY = new armory.logicnode.VectorAngles2D(this);
		_VectorAngles2DXY.addInput(new armory.logicnode.VectorNode(this, 1.0, 0.0, 0.0), 0);
		_VectorAngles2DXY.addInput(_VectorFromTransform, 0);
		var _RotateVectorAroundAxis = new armory.logicnode.RotateVectorAroundAxisNode(this);
		var _VectorMath_003 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_003.property0 = "Multiply";
		var _MouseCoords = new armory.logicnode.MouseCoordsNode(this);
		_MouseCoords.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_MouseCoords.addOutputs([_VectorMath_003]);
		_MouseCoords.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_VectorMath_003.addInput(_MouseCoords, 1);
		_VectorMath_003.addInput(new armory.logicnode.VectorNode(this, -0.10000000149011612, 0.10000000149011612, 0.0), 0);
		_VectorMath_003.addOutputs([_RotateVectorAroundAxis]);
		_VectorMath_003.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_RotateVectorAroundAxis.addInput(_VectorMath_003, 0);
		_RotateVectorAroundAxis.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 1.0), 0);
		_RotateVectorAroundAxis.addInput(_VectorAngles2DXY, 0);
		_RotateVectorAroundAxis.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_RotateVectorAroundAxis.addOutputs([_TranslateObject]);
		_RotateVectorAroundAxis.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_VectorAngles2DXY.addOutputs([_RotateVectorAroundAxis]);
		_VectorAngles2DXY.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_VectorFromTransform.addOutputs([_VectorAngles2DXY]);
		_GetTransform.addOutputs([_VectorFromTransform]);
		_ActiveCamera.addOutputs([_GetTransform, _TranslateObject]);
		_TranslateObject.addInput(_ActiveCamera, 0);
		_TranslateObject.addInput(_RotateVectorAroundAxis, 1);
		_TranslateObject.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_TranslateObject.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate.addOutputs([_TranslateObject]);
		_TranslateObject_002.addInput(_Gate, 0);
		var _GetProperty_029 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_008 = new armory.logicnode.GlobalObjectNode(this);
		var _GetProperty_030 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_030.addInput(_GlobalObject_008, 0);
		_GetProperty_030.addInput(new armory.logicnode.StringNode(this, "Object_move_arrows"), 0);
		var _TranslateObject_003 = new armory.logicnode.TranslateObjectNode(this);
		_TranslateObject_003.addInput(_TranslateObject_002, 0);
		_TranslateObject_003.addInput(_GetProperty_030, 0);
		var _RotateVectorAroundAxis_001 = new armory.logicnode.RotateVectorAroundAxisNode(this);
		var _VectorMath_005 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_005.property0 = "Multiply";
		var _MouseCoords_005 = new armory.logicnode.MouseCoordsNode(this);
		_MouseCoords_005.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_MouseCoords_005.addOutputs([_VectorMath_005]);
		_MouseCoords_005.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_VectorMath_005.addInput(_MouseCoords_005, 1);
		_VectorMath_005.addInput(new armory.logicnode.VectorNode(this, 0.05000000074505806, -0.05000000074505806, 0.0), 0);
		_VectorMath_005.addOutputs([_RotateVectorAroundAxis_001]);
		_VectorMath_005.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_RotateVectorAroundAxis_001.addInput(_VectorMath_005, 0);
		_RotateVectorAroundAxis_001.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 1.0), 0);
		var _VectorAngles2DXY_001 = new armory.logicnode.VectorAngles2D(this);
		_VectorAngles2DXY_001.addInput(new armory.logicnode.VectorNode(this, 1.0, 0.0, 0.0), 0);
		var _VectorFromTransform_001 = new armory.logicnode.VectorFromTransformNode(this);
		_VectorFromTransform_001.property0 = "Right";
		var _GetTransform_001 = new armory.logicnode.GetTransformNode(this);
		var _ActiveCamera_003 = new armory.logicnode.ActiveCameraNode(this);
		_ActiveCamera_003.addOutputs([_GetTransform_001]);
		_GetTransform_001.addInput(_ActiveCamera_003, 0);
		_GetTransform_001.addOutputs([_VectorFromTransform_001]);
		_VectorFromTransform_001.addInput(_GetTransform_001, 0);
		_VectorFromTransform_001.addOutputs([_VectorAngles2DXY_001]);
		_VectorAngles2DXY_001.addInput(_VectorFromTransform_001, 0);
		_VectorAngles2DXY_001.addOutputs([_RotateVectorAroundAxis_001]);
		_VectorAngles2DXY_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_RotateVectorAroundAxis_001.addInput(_VectorAngles2DXY_001, 0);
		_RotateVectorAroundAxis_001.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_RotateVectorAroundAxis_001.addOutputs([_TranslateObject_002, _TranslateObject_003]);
		_RotateVectorAroundAxis_001.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_TranslateObject_003.addInput(_RotateVectorAroundAxis_001, 1);
		_TranslateObject_003.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_TranslateObject_003.addOutputs([_Merge]);
		_GetProperty_030.addOutputs([_TranslateObject_003]);
		_GetProperty_030.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_GlobalObject_008.addOutputs([_GetProperty_030, _GetProperty_029]);
		_GetProperty_029.addInput(_GlobalObject_008, 0);
		_GetProperty_029.addInput(new armory.logicnode.StringNode(this, "Object_to_move"), 0);
		_GetProperty_029.addOutputs([_TranslateObject_002]);
		_GetProperty_029.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_TranslateObject_002.addInput(_GetProperty_029, 0);
		_TranslateObject_002.addInput(_RotateVectorAroundAxis_001, 1);
		_TranslateObject_002.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_TranslateObject_002.addOutputs([_TranslateObject_003, _Merge]);
		_Merge.addInput(_TranslateObject_002, 0);
		_Merge.addInput(_TranslateObject_003, 0);
		_Merge.addInput(new armory.logicnode.NullNode(this), 0);
		_Merge.addInput(new armory.logicnode.NullNode(this), 0);
		_Merge.addInput(new armory.logicnode.NullNode(this), 0);
		_Merge.addInput(new armory.logicnode.NullNode(this), 0);
		_Merge.addOutputs([_SendGlobalEvent]);
		_SendGlobalEvent.addInput(_Merge, 0);
		_SendGlobalEvent.addInput(new armory.logicnode.StringNode(this, "Calc_Beams"), 0);
		_SendGlobalEvent.addOutputs([new armory.logicnode.NullNode(this)]);
		var _RemoveObject_001 = new armory.logicnode.RemoveObjectNode(this);
		var _Gate_001 = new armory.logicnode.GateNode(this);
		_Gate_001.property0 = "And";
		_Gate_001.property1 = 9.999999747378752e-05;
		var _OnMouse_001 = new armory.logicnode.OnMouseNode(this);
		_OnMouse_001.property0 = "Released";
		_OnMouse_001.property1 = "left";
		_OnMouse_001.addOutputs([_Gate_001]);
		_Gate_001.addInput(_OnMouse_001, 0);
		var _GetProperty_012 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_011 = new armory.logicnode.GlobalObjectNode(this);
		var _GetProperty_009 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_009.addInput(_GlobalObject_011, 0);
		_GetProperty_009.addInput(new armory.logicnode.StringNode(this, "move_permission"), 0);
		_GetProperty_009.addOutputs([_Gate_001]);
		_GetProperty_009.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_GlobalObject_011.addOutputs([_GetProperty_012, _GetProperty_009]);
		_GetProperty_012.addInput(_GlobalObject_011, 0);
		_GetProperty_012.addInput(new armory.logicnode.StringNode(this, "Object_movable"), 0);
		_GetProperty_012.addOutputs([_Gate_001]);
		_GetProperty_012.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Gate_001.addInput(_GetProperty_012, 0);
		_Gate_001.addInput(_GetProperty_009, 0);
		_Gate_001.addOutputs([_RemoveObject_001]);
		_Gate_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_RemoveObject_001.addInput(_Gate_001, 0);
		var _GetProperty_014 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_012 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_012.addOutputs([_GetProperty_014]);
		_GetProperty_014.addInput(_GlobalObject_012, 0);
		_GetProperty_014.addInput(new armory.logicnode.StringNode(this, "Object_move_arrows"), 0);
		_GetProperty_014.addOutputs([_RemoveObject_001]);
		_GetProperty_014.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_RemoveObject_001.addInput(_GetProperty_014, 0);
		_RemoveObject_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _RemoveObject = new armory.logicnode.RemoveObjectNode(this);
		var _OnKeyboard_002 = new armory.logicnode.OnKeyboardNode(this);
		_OnKeyboard_002.property0 = "Started";
		_OnKeyboard_002.property1 = "delete";
		_OnKeyboard_002.addOutputs([_RemoveObject]);
		_RemoveObject.addInput(_OnKeyboard_002, 0);
		var _PickObject_002 = new armory.logicnode.PickObjectNode(this);
		var _MouseCoords_004 = new armory.logicnode.MouseCoordsNode(this);
		_MouseCoords_004.addOutputs([_PickObject_002]);
		_MouseCoords_004.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_MouseCoords_004.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_PickObject_002.addInput(_MouseCoords_004, 0);
		_PickObject_002.addOutputs([_RemoveObject]);
		_PickObject_002.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_RemoveObject.addInput(_PickObject_002, 0);
		_RemoveObject.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_007 = new armory.logicnode.SetPropertyNode(this);
		var _SetLocation_003 = new armory.logicnode.SetLocationNode(this);
		var _SetProperty_006 = new armory.logicnode.SetPropertyNode(this);
		var _SpawnObject_002 = new armory.logicnode.SpawnObjectNode(this);
		var _IsTrue_001 = new armory.logicnode.IsTrueNode(this);
		var _SetProperty_004 = new armory.logicnode.SetPropertyNode(this);
		var _SetProperty_001 = new armory.logicnode.SetPropertyNode(this);
		var _OnMouse_003 = new armory.logicnode.OnMouseNode(this);
		_OnMouse_003.property0 = "Started";
		_OnMouse_003.property1 = "left";
		_OnMouse_003.addOutputs([_SetProperty_001]);
		_SetProperty_001.addInput(_OnMouse_003, 0);
		var _GlobalObject_001 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_001.addOutputs([_SetProperty_001, _SetProperty_004]);
		_SetProperty_001.addInput(_GlobalObject_001, 0);
		_SetProperty_001.addInput(new armory.logicnode.StringNode(this, "Object_movable"), 0);
		var _GetProperty_004 = new armory.logicnode.GetPropertyNode(this);
		var _PickObject = new armory.logicnode.PickObjectNode(this);
		var _MouseCoords_002 = new armory.logicnode.MouseCoordsNode(this);
		_MouseCoords_002.addOutputs([_PickObject]);
		_MouseCoords_002.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_MouseCoords_002.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_PickObject.addInput(_MouseCoords_002, 0);
		_PickObject.addOutputs([_GetProperty_004, _SetProperty_004]);
		_PickObject.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_GetProperty_004.addInput(_PickObject, 0);
		_GetProperty_004.addInput(new armory.logicnode.StringNode(this, "movable"), 0);
		_GetProperty_004.addOutputs([_SetProperty_001]);
		_GetProperty_004.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_SetProperty_001.addInput(_GetProperty_004, 0);
		_SetProperty_001.addOutputs([_SetProperty_004]);
		_SetProperty_004.addInput(_SetProperty_001, 0);
		_SetProperty_004.addInput(_GlobalObject_001, 0);
		_SetProperty_004.addInput(new armory.logicnode.StringNode(this, "Object_to_move"), 0);
		_SetProperty_004.addInput(_PickObject, 0);
		_SetProperty_004.addOutputs([_IsTrue_001]);
		_IsTrue_001.addInput(_SetProperty_004, 0);
		var _GetProperty_007 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_002 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_002.addOutputs([_GetProperty_007]);
		_GetProperty_007.addInput(_GlobalObject_002, 0);
		_GetProperty_007.addInput(new armory.logicnode.StringNode(this, "Object_movable"), 0);
		_GetProperty_007.addOutputs([_IsTrue_001]);
		_GetProperty_007.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_IsTrue_001.addInput(_GetProperty_007, 0);
		_IsTrue_001.addOutputs([_SpawnObject_002]);
		_SpawnObject_002.addInput(_IsTrue_001, 0);
		_SpawnObject_002.addInput(new armory.logicnode.ObjectNode(this, "Movement_arrows"), 0);
		_SpawnObject_002.addInput(new armory.logicnode.NullNode(this), 0);
		_SpawnObject_002.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_SpawnObject_002.addOutputs([_SetProperty_006]);
		_SpawnObject_002.addOutputs([_SetLocation_003, _SetProperty_006]);
		_SetProperty_006.addInput(_SpawnObject_002, 0);
		var _GlobalObject_003 = new armory.logicnode.GlobalObjectNode(this);
		var _GetProperty_010 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_010.addInput(_GlobalObject_003, 0);
		_GetProperty_010.addInput(new armory.logicnode.StringNode(this, "Object_to_move"), 0);
		var _GetLocation_001 = new armory.logicnode.GetLocationNode(this);
		_GetLocation_001.addInput(_GetProperty_010, 0);
		_GetLocation_001.addOutputs([_SetLocation_003]);
		_GetProperty_010.addOutputs([_GetLocation_001]);
		_GetProperty_010.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_GlobalObject_003.addOutputs([_GetProperty_010, _SetProperty_006]);
		_SetProperty_006.addInput(_GlobalObject_003, 0);
		_SetProperty_006.addInput(new armory.logicnode.StringNode(this, "Object_move_arrows"), 0);
		_SetProperty_006.addInput(_SpawnObject_002, 1);
		_SetProperty_006.addOutputs([_SetLocation_003]);
		_SetLocation_003.addInput(_SetProperty_006, 0);
		_SetLocation_003.addInput(_SpawnObject_002, 1);
		_SetLocation_003.addInput(_GetLocation_001, 0);
		_SetLocation_003.addOutputs([_SetProperty_007]);
		_SetProperty_007.addInput(_SetLocation_003, 0);
		var _GlobalObject_004 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_004.addOutputs([_SetProperty_007]);
		_SetProperty_007.addInput(_GlobalObject_004, 0);
		_SetProperty_007.addInput(new armory.logicnode.StringNode(this, "move_permission"), 0);
		var _Boolean_002 = new armory.logicnode.BooleanNode(this);
		_Boolean_002.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_Boolean_002.addOutputs([_SetProperty_007]);
		_SetProperty_007.addInput(_Boolean_002, 0);
		_SetProperty_007.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_015 = new armory.logicnode.SetPropertyNode(this);
		var _OnInit_002 = new armory.logicnode.OnInitNode(this);
		var _SetProperty_010 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_010.addInput(_OnInit_002, 0);
		var _GlobalObject = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject.addOutputs([_SetProperty_010, _SetProperty_015]);
		_SetProperty_010.addInput(_GlobalObject, 0);
		_SetProperty_010.addInput(new armory.logicnode.StringNode(this, "move_permission"), 0);
		var _Boolean_003 = new armory.logicnode.BooleanNode(this);
		_Boolean_003.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_Boolean_003.addOutputs([_SetProperty_010]);
		_SetProperty_010.addInput(_Boolean_003, 0);
		_SetProperty_010.addOutputs([new armory.logicnode.NullNode(this)]);
		_OnInit_002.addOutputs([_SetProperty_010, _SetProperty_015]);
		_SetProperty_015.addInput(_OnInit_002, 0);
		_SetProperty_015.addInput(_GlobalObject, 0);
		_SetProperty_015.addInput(new armory.logicnode.StringNode(this, "rot_speed"), 0);
		var _Float_001 = new armory.logicnode.FloatNode(this);
		_Float_001.addInput(new armory.logicnode.FloatNode(this, 0.009999999776482582), 0);
		_Float_001.addOutputs([_SetProperty_015]);
		_SetProperty_015.addInput(_Float_001, 0);
		_SetProperty_015.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_003 = new armory.logicnode.SetPropertyNode(this);
		var _OnInit_001 = new armory.logicnode.OnInitNode(this);
		_OnInit_001.addOutputs([_SetProperty_003]);
		_SetProperty_003.addInput(_OnInit_001, 0);
		var _Self_009 = new armory.logicnode.SelfNode(this);
		_Self_009.addOutputs([_SetProperty_003]);
		_SetProperty_003.addInput(_Self_009, 0);
		_SetProperty_003.addInput(new armory.logicnode.StringNode(this, "speed"), 0);
		var _Vector_001 = new armory.logicnode.VectorNode(this);
		var _Float = new armory.logicnode.FloatNode(this);
		_Float.addInput(new armory.logicnode.FloatNode(this, 0.02500000037252903), 0);
		_Float.addOutputs([_Vector_001, _Vector_001]);
		_Vector_001.addInput(_Float, 0);
		_Vector_001.addInput(_Float, 0);
		_Vector_001.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_001.addOutputs([_SetProperty_003]);
		_SetProperty_003.addInput(_Vector_001, 0);
		_SetProperty_003.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty = new armory.logicnode.SetPropertyNode(this);
		var _OnInit = new armory.logicnode.OnInitNode(this);
		_OnInit.addOutputs([_SetProperty]);
		_SetProperty.addInput(_OnInit, 0);
		var _Self_005 = new armory.logicnode.SelfNode(this);
		_Self_005.addOutputs([_SetProperty]);
		_SetProperty.addInput(_Self_005, 0);
		_SetProperty.addInput(new armory.logicnode.StringNode(this, "Object_movable"), 0);
		var _Boolean = new armory.logicnode.BooleanNode(this);
		_Boolean.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_Boolean.addOutputs([_SetProperty]);
		_SetProperty.addInput(_Boolean, 0);
		_SetProperty.addOutputs([new armory.logicnode.NullNode(this)]);
		var _RotateObject = new armory.logicnode.RotateObjectNode(this);
		var _Node = new armory.logicnode.OnMouseNode(this);
		_Node.property0 = "Down";
		_Node.property1 = "middle";
		var _RotateObjectAroundAxis_002 = new armory.logicnode.RotateObjectAroundAxisNode(this);
		_RotateObjectAroundAxis_002.addInput(_Node, 0);
		var _ActiveCamera_002 = new armory.logicnode.ActiveCameraNode(this);
		_ActiveCamera_002.addOutputs([_RotateObjectAroundAxis_002, _RotateObject]);
		_RotateObjectAroundAxis_002.addInput(_ActiveCamera_002, 0);
		_RotateObjectAroundAxis_002.addInput(new armory.logicnode.VectorNode(this, 0.0, 0.0, 1.0), 0);
		var _SeparateXYZ_001 = new armory.logicnode.SeparateVectorNode(this);
		var _VectorMath_004 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_004.property0 = "Multiply";
		var _MouseCoords_003 = new armory.logicnode.MouseCoordsNode(this);
		_MouseCoords_003.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_MouseCoords_003.addOutputs([_VectorMath_004]);
		_MouseCoords_003.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_VectorMath_004.addInput(_MouseCoords_003, 1);
		_VectorMath_004.addInput(new armory.logicnode.VectorNode(this, -0.004999999888241291, -0.004999999888241291, 0.0), 0);
		_VectorMath_004.addOutputs([_SeparateXYZ_001]);
		_VectorMath_004.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_001.addInput(_VectorMath_004, 0);
		_SeparateXYZ_001.addOutputs([_RotateObjectAroundAxis_002]);
		var _Vector_004 = new armory.logicnode.VectorNode(this);
		_Vector_004.addInput(_SeparateXYZ_001, 1);
		_Vector_004.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_004.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_004.addOutputs([_RotateObject]);
		_SeparateXYZ_001.addOutputs([_Vector_004]);
		_SeparateXYZ_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_RotateObjectAroundAxis_002.addInput(_SeparateXYZ_001, 0);
		_RotateObjectAroundAxis_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_Node.addOutputs([_RotateObject, _RotateObjectAroundAxis_002]);
		_RotateObject.addInput(_Node, 0);
		_RotateObject.addInput(_ActiveCamera_002, 0);
		_RotateObject.addInput(_Vector_004, 0);
		_RotateObject.addOutputs([new armory.logicnode.NullNode(this)]);
		var _TranslateObject_001 = new armory.logicnode.TranslateObjectNode(this);
		var _Gate_002 = new armory.logicnode.GateNode(this);
		_Gate_002.property0 = "Equal";
		_Gate_002.property1 = 9.999999747378752e-05;
		var _OnUpdate = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate.property0 = "Update";
		_OnUpdate.addOutputs([_Gate_002]);
		_Gate_002.addInput(_OnUpdate, 0);
		var _MouseCoords_001 = new armory.logicnode.MouseCoordsNode(this);
		_MouseCoords_001.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_MouseCoords_001.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		var _Vector_003 = new armory.logicnode.VectorNode(this);
		_Vector_003.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_003.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_003.addInput(_MouseCoords_001, 2);
		_Vector_003.addOutputs([_TranslateObject_001]);
		_MouseCoords_001.addOutputs([_Gate_002, _Vector_003]);
		_Gate_002.addInput(_MouseCoords_001, 2);
		var _Integer = new armory.logicnode.IntegerNode(this);
		_Integer.addInput(new armory.logicnode.IntegerNode(this, 0), 0);
		_Integer.addOutputs([_Gate_002]);
		_Gate_002.addInput(_Integer, 0);
		_Gate_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_002.addOutputs([_TranslateObject_001]);
		_TranslateObject_001.addInput(_Gate_002, 1);
		var _ActiveCamera_001 = new armory.logicnode.ActiveCameraNode(this);
		_ActiveCamera_001.addOutputs([_TranslateObject_001]);
		_TranslateObject_001.addInput(_ActiveCamera_001, 0);
		_TranslateObject_001.addInput(_Vector_003, 0);
		_TranslateObject_001.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_TranslateObject_001.addOutputs([new armory.logicnode.NullNode(this)]);
	}
}