package arm.node;

@:keep class Kamera_Bewegung_001 extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		name = "Kamera_Bewegung_001";
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _SendGlobalEvent = new armory.logicnode.SendGlobalEventNode(this);
		var _OnUpdate = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate.property0 = "Update";
		_OnUpdate.addOutputs([_SendGlobalEvent]);
		_SendGlobalEvent.addInput(_OnUpdate, 0);
		_SendGlobalEvent.addInput(new armory.logicnode.StringNode(this, "Calc_Beams"), 0);
		_SendGlobalEvent.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetTransform_001 = new armory.logicnode.SetTransformNode(this);
		var _OnUpdate_002 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_002.property0 = "Update";
		var _Gate_007 = new armory.logicnode.GateNode(this);
		_Gate_007.property0 = "Equal";
		_Gate_007.property1 = 9.999999747378752e-05;
		_Gate_007.addInput(_OnUpdate_002, 0);
		var _PickObject_002 = new armory.logicnode.PickObjectNode(this);
		var _MouseCoords_002 = new armory.logicnode.MouseCoordsNode(this);
		_MouseCoords_002.addOutputs([_PickObject_002]);
		var _VectorMath = new armory.logicnode.VectorMathNode(this);
		_VectorMath.property0 = "Multiply";
		_VectorMath.addInput(_MouseCoords_002, 1);
		_VectorMath.addInput(new armory.logicnode.VectorNode(this, 0.05000000074505806, 0.0, 0.0), 0);
		var _SeparateXYZ_010 = new armory.logicnode.SeparateVectorNode(this);
		_SeparateXYZ_010.addInput(_VectorMath, 0);
		var _Math_012 = new armory.logicnode.MathNode(this);
		_Math_012.property0 = "Add";
		_Math_012.property1 = "false";
		var _SeparateXYZ_008 = new armory.logicnode.SeparateVectorNode(this);
		var _GetLocation = new armory.logicnode.GetLocationNode(this);
		_GetLocation.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetLocation.addOutputs([_SeparateXYZ_008]);
		_SeparateXYZ_008.addInput(_GetLocation, 0);
		var _Print = new armory.logicnode.PrintNode(this);
		var _OnUpdate_004 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_004.property0 = "Update";
		_OnUpdate_004.addOutputs([_Print]);
		_Print.addInput(_OnUpdate_004, 0);
		_Print.addInput(_SeparateXYZ_008, 0);
		_Print.addOutputs([new armory.logicnode.NullNode(this)]);
		_SeparateXYZ_008.addOutputs([_Print, _Math_012]);
		_SeparateXYZ_008.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_008.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Math_012.addInput(_SeparateXYZ_008, 0);
		_Math_012.addInput(_SeparateXYZ_010, 0);
		var _Gate_016 = new armory.logicnode.GateNode(this);
		_Gate_016.property0 = "Greater Equal";
		_Gate_016.property1 = 9.999999747378752e-05;
		var _Gate_004 = new armory.logicnode.GateNode(this);
		_Gate_004.property0 = "Equal";
		_Gate_004.property1 = 9.999999747378752e-05;
		var _OnMouse = new armory.logicnode.OnMouseNode(this);
		_OnMouse.property0 = "Down";
		_OnMouse.property1 = "middle";
		_OnMouse.addOutputs([_Gate_004]);
		_Gate_004.addInput(_OnMouse, 0);
		var _Object_003 = new armory.logicnode.ObjectNode(this);
		_Object_003.addInput(new armory.logicnode.ObjectNode(this, "Weltkugel_Maus_Navigation"), 0);
		var _Gate_005 = new armory.logicnode.GateNode(this);
		_Gate_005.property0 = "Equal";
		_Gate_005.property1 = 9.999999747378752e-05;
		var _OnUpdate_001 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_001.property0 = "Update";
		_OnUpdate_001.addOutputs([_Gate_005]);
		_Gate_005.addInput(_OnUpdate_001, 0);
		_Gate_005.addInput(_Object_003, 0);
		_Gate_005.addInput(_PickObject_002, 0);
		var _Gate_013 = new armory.logicnode.GateNode(this);
		_Gate_013.property0 = "Greater Equal";
		_Gate_013.property1 = 9.999999747378752e-05;
		_Gate_013.addInput(_Gate_005, 0);
		var _Math_006 = new armory.logicnode.MathNode(this);
		_Math_006.property0 = "Add";
		_Math_006.property1 = "false";
		var _GetDistance = new armory.logicnode.GetDistanceNode(this);
		_GetDistance.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetDistance.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetDistance.addOutputs([_Math_006]);
		_Math_006.addInput(_GetDistance, 0);
		var _Math_011 = new armory.logicnode.MathNode(this);
		_Math_011.property0 = "Multiply";
		_Math_011.property1 = "false";
		_Math_011.addInput(_MouseCoords_002, 2);
		_Math_011.addInput(new armory.logicnode.FloatNode(this, 4.0), 0);
		var _Vector_003 = new armory.logicnode.VectorNode(this);
		_Vector_003.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_003.addInput(_Math_011, 0);
		_Vector_003.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		var _TranslateObject_001 = new armory.logicnode.TranslateObjectNode(this);
		var _Gate_014 = new armory.logicnode.GateNode(this);
		_Gate_014.property0 = "Less Equal";
		_Gate_014.property1 = 9.999999747378752e-05;
		_Gate_014.addInput(_Gate_013, 0);
		_Gate_014.addInput(_Math_006, 0);
		var _Float_005 = new armory.logicnode.FloatNode(this);
		_Float_005.addInput(new armory.logicnode.FloatNode(this, 440.0), 0);
		_Float_005.addOutputs([_Gate_014]);
		_Gate_014.addInput(_Float_005, 0);
		_Gate_014.addOutputs([_TranslateObject_001]);
		_TranslateObject_001.addInput(_Gate_014, 0);
		_TranslateObject_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_TranslateObject_001.addInput(_Vector_003, 0);
		_TranslateObject_001.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_TranslateObject_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Vector_003.addOutputs([_TranslateObject_001]);
		_Math_011.addOutputs([_Vector_003, _Math_006]);
		_Math_006.addInput(_Math_011, 0);
		_Math_006.addOutputs([_Gate_013, _Gate_014]);
		_Gate_013.addInput(_Math_006, 0);
		var _Float_004 = new armory.logicnode.FloatNode(this);
		_Float_004.addInput(new armory.logicnode.FloatNode(this, 50.0), 0);
		_Float_004.addOutputs([_Gate_013]);
		_Gate_013.addInput(_Float_004, 0);
		_Gate_013.addOutputs([_Gate_014]);
		_Gate_005.addOutputs([_Gate_013]);
		var _Gate_006 = new armory.logicnode.GateNode(this);
		_Gate_006.property0 = "Equal";
		_Gate_006.property1 = 9.999999747378752e-05;
		var _OnMouse_002 = new armory.logicnode.OnMouseNode(this);
		_OnMouse_002.property0 = "Started";
		_OnMouse_002.property1 = "left";
		_OnMouse_002.addOutputs([_Gate_006]);
		_Gate_006.addInput(_OnMouse_002, 0);
		_Gate_006.addInput(_Object_003, 0);
		_Gate_006.addInput(_PickObject_002, 0);
		var _SetProperty = new armory.logicnode.SetPropertyNode(this);
		_SetProperty.addInput(_Gate_006, 0);
		_SetProperty.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetProperty.addInput(new armory.logicnode.StringNode(this, "Maus"), 0);
		var _String = new armory.logicnode.StringNode(this);
		_String.addInput(new armory.logicnode.StringNode(this, "An"), 0);
		var _Gate_008 = new armory.logicnode.GateNode(this);
		_Gate_008.property0 = "Equal";
		_Gate_008.property1 = 9.999999747378752e-05;
		var _OnMouse_001 = new armory.logicnode.OnMouseNode(this);
		_OnMouse_001.property0 = "Down";
		_OnMouse_001.property1 = "left";
		_OnMouse_001.addOutputs([_Gate_008]);
		_Gate_008.addInput(_OnMouse_001, 0);
		_Gate_008.addInput(_String, 0);
		var _GetProperty = new armory.logicnode.GetPropertyNode(this);
		_GetProperty.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetProperty.addInput(new armory.logicnode.StringNode(this, "Maus"), 0);
		_GetProperty.addOutputs([_Gate_008]);
		_GetProperty.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Gate_008.addInput(_GetProperty, 0);
		var _Gate_009 = new armory.logicnode.GateNode(this);
		_Gate_009.property0 = "Greater Equal";
		_Gate_009.property1 = 9.999999747378752e-05;
		_Gate_009.addInput(_Gate_008, 0);
		var _Math_009 = new armory.logicnode.MathNode(this);
		_Math_009.property0 = "Add";
		_Math_009.property1 = "false";
		var _SeparateXYZ_009 = new armory.logicnode.SeparateVectorNode(this);
		var _GetRotation_001 = new armory.logicnode.GetRotationNode(this);
		_GetRotation_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetRotation_001.addOutputs([_SeparateXYZ_009]);
		_GetRotation_001.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_GetRotation_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_GetRotation_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_GetRotation_001.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_GetRotation_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_009.addInput(_GetRotation_001, 0);
		_SeparateXYZ_009.addOutputs([_Math_009]);
		_SeparateXYZ_009.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_009.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Math_009.addInput(_SeparateXYZ_009, 0);
		var _Math_008 = new armory.logicnode.MathNode(this);
		_Math_008.property0 = "Multiply";
		_Math_008.property1 = "false";
		var _SeparateXYZ_007 = new armory.logicnode.SeparateVectorNode(this);
		_SeparateXYZ_007.addInput(_MouseCoords_002, 1);
		_SeparateXYZ_007.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_007.addOutputs([_Math_008]);
		_SeparateXYZ_007.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Math_008.addInput(_SeparateXYZ_007, 1);
		_Math_008.addInput(new armory.logicnode.FloatNode(this, 0.004999999888241291), 0);
		var _Vector_001 = new armory.logicnode.VectorNode(this);
		_Vector_001.addInput(_Math_008, 0);
		_Vector_001.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_001.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		var _RotateObject_001 = new armory.logicnode.RotateObjectNode(this);
		var _Gate_010 = new armory.logicnode.GateNode(this);
		_Gate_010.property0 = "Less Equal";
		_Gate_010.property1 = 9.999999747378752e-05;
		_Gate_010.addInput(_Gate_009, 0);
		_Gate_010.addInput(_Math_009, 0);
		var _Float_001 = new armory.logicnode.FloatNode(this);
		_Float_001.addInput(new armory.logicnode.FloatNode(this, 1.570796012878418), 0);
		_Float_001.addOutputs([_Gate_010]);
		_Gate_010.addInput(_Float_001, 0);
		_Gate_010.addOutputs([_RotateObject_001]);
		_RotateObject_001.addInput(_Gate_010, 0);
		_RotateObject_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_RotateObject_001.addInput(_Vector_001, 0);
		_RotateObject_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Vector_001.addOutputs([_RotateObject_001]);
		_Math_008.addOutputs([_Vector_001, _Math_009]);
		_Math_009.addInput(_Math_008, 0);
		_Math_009.addOutputs([_Gate_009, _Gate_010]);
		_Gate_009.addInput(_Math_009, 0);
		var _Float = new armory.logicnode.FloatNode(this);
		_Float.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Float.addOutputs([_Gate_009]);
		_Gate_009.addInput(_Float, 0);
		_Gate_009.addOutputs([_Gate_010]);
		var _Gate_011 = new armory.logicnode.GateNode(this);
		_Gate_011.property0 = "Greater Equal";
		_Gate_011.property1 = 9.999999747378752e-05;
		_Gate_011.addInput(_Gate_008, 0);
		var _Math_010 = new armory.logicnode.MathNode(this);
		_Math_010.property0 = "Add";
		_Math_010.property1 = "false";
		var _SeparateXYZ_011 = new armory.logicnode.SeparateVectorNode(this);
		var _GetRotation_002 = new armory.logicnode.GetRotationNode(this);
		_GetRotation_002.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetRotation_002.addOutputs([_SeparateXYZ_011]);
		_GetRotation_002.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_GetRotation_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_GetRotation_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_GetRotation_002.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_GetRotation_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_011.addInput(_GetRotation_002, 0);
		_SeparateXYZ_011.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_011.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_011.addOutputs([_Math_010]);
		_Math_010.addInput(_SeparateXYZ_011, 2);
		var _Math_007 = new armory.logicnode.MathNode(this);
		_Math_007.property0 = "Multiply";
		_Math_007.property1 = "false";
		var _SeparateXYZ_006 = new armory.logicnode.SeparateVectorNode(this);
		_SeparateXYZ_006.addInput(_MouseCoords_002, 1);
		_SeparateXYZ_006.addOutputs([_Math_007]);
		_SeparateXYZ_006.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_006.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Math_007.addInput(_SeparateXYZ_006, 0);
		_Math_007.addInput(new armory.logicnode.FloatNode(this, -0.004999999888241291), 0);
		var _Vector = new armory.logicnode.VectorNode(this);
		_Vector.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector.addInput(_Math_007, 0);
		var _RotateObject = new armory.logicnode.RotateObjectNode(this);
		var _Gate_012 = new armory.logicnode.GateNode(this);
		_Gate_012.property0 = "Less Equal";
		_Gate_012.property1 = 9.999999747378752e-05;
		_Gate_012.addInput(_Gate_011, 0);
		_Gate_012.addInput(_Math_010, 0);
		var _Float_003 = new armory.logicnode.FloatNode(this);
		_Float_003.addInput(new armory.logicnode.FloatNode(this, 1.2999999523162842), 0);
		_Float_003.addOutputs([_Gate_012]);
		_Gate_012.addInput(_Float_003, 0);
		_Gate_012.addOutputs([_RotateObject]);
		_RotateObject.addInput(_Gate_012, 0);
		_RotateObject.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_RotateObject.addInput(_Vector, 0);
		_RotateObject.addOutputs([new armory.logicnode.NullNode(this)]);
		_Vector.addOutputs([_RotateObject]);
		_Math_007.addOutputs([_Vector, _Math_010]);
		_Math_010.addInput(_Math_007, 0);
		_Math_010.addOutputs([_Gate_011, _Gate_012]);
		_Gate_011.addInput(_Math_010, 0);
		var _Float_002 = new armory.logicnode.FloatNode(this);
		_Float_002.addInput(new armory.logicnode.FloatNode(this, -1.2999999523162842), 0);
		_Float_002.addOutputs([_Gate_011]);
		_Gate_011.addInput(_Float_002, 0);
		_Gate_011.addOutputs([_Gate_012]);
		_Gate_008.addOutputs([_Gate_009, _Gate_011]);
		_String.addOutputs([_SetProperty, _Gate_008]);
		_SetProperty.addInput(_String, 0);
		_SetProperty.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_006.addOutputs([_SetProperty]);
		var _Gate = new armory.logicnode.GateNode(this);
		_Gate.property0 = "Equal";
		_Gate.property1 = 9.999999747378752e-05;
		var _OnUpdate_003 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_003.property0 = "Update";
		var _CanvasSetLocation = new armory.logicnode.CanvasSetLocationNode(this);
		_CanvasSetLocation.addInput(_OnUpdate_003, 0);
		_CanvasSetLocation.addInput(new armory.logicnode.StringNode(this, "Objektbeschriftung"), 0);
		var _Math = new armory.logicnode.MathNode(this);
		_Math.property0 = "Add";
		_Math.property1 = "false";
		var _SeparateXYZ_001 = new armory.logicnode.SeparateVectorNode(this);
		var _MouseCoords_006 = new armory.logicnode.MouseCoordsNode(this);
		_MouseCoords_006.addOutputs([_SeparateXYZ_001]);
		_MouseCoords_006.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_MouseCoords_006.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_SeparateXYZ_001.addInput(_MouseCoords_006, 0);
		var _CanvasSetLocation_001 = new armory.logicnode.CanvasSetLocationNode(this);
		_CanvasSetLocation_001.addInput(_OnUpdate_003, 0);
		_CanvasSetLocation_001.addInput(new armory.logicnode.StringNode(this, "Linie"), 0);
		_CanvasSetLocation_001.addInput(_SeparateXYZ_001, 0);
		var _Math_003 = new armory.logicnode.MathNode(this);
		_Math_003.property0 = "Add";
		_Math_003.property1 = "false";
		_Math_003.addInput(_SeparateXYZ_001, 1);
		_Math_003.addInput(new armory.logicnode.FloatNode(this, -65.0), 0);
		_Math_003.addOutputs([_CanvasSetLocation_001]);
		_CanvasSetLocation_001.addInput(_Math_003, 0);
		_CanvasSetLocation_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Math_004 = new armory.logicnode.MathNode(this);
		_Math_004.property0 = "Add";
		_Math_004.property1 = "false";
		_Math_004.addInput(_SeparateXYZ_001, 0);
		_Math_004.addInput(new armory.logicnode.FloatNode(this, 10.0), 0);
		var _CanvasSetLocation_002 = new armory.logicnode.CanvasSetLocationNode(this);
		_CanvasSetLocation_002.addInput(_OnUpdate_003, 0);
		_CanvasSetLocation_002.addInput(new armory.logicnode.StringNode(this, "erste"), 0);
		_CanvasSetLocation_002.addInput(_Math_004, 0);
		var _Math_002 = new armory.logicnode.MathNode(this);
		_Math_002.property0 = "Add";
		_Math_002.property1 = "false";
		_Math_002.addInput(_SeparateXYZ_001, 1);
		_Math_002.addInput(new armory.logicnode.FloatNode(this, -60.0), 0);
		_Math_002.addOutputs([_CanvasSetLocation_002]);
		_CanvasSetLocation_002.addInput(_Math_002, 0);
		_CanvasSetLocation_002.addOutputs([new armory.logicnode.NullNode(this)]);
		var _CanvasSetLocation_003 = new armory.logicnode.CanvasSetLocationNode(this);
		_CanvasSetLocation_003.addInput(_OnUpdate_003, 0);
		_CanvasSetLocation_003.addInput(new armory.logicnode.StringNode(this, "zweite"), 0);
		_CanvasSetLocation_003.addInput(_Math_004, 0);
		var _Math_005 = new armory.logicnode.MathNode(this);
		_Math_005.property0 = "Add";
		_Math_005.property1 = "false";
		_Math_005.addInput(_SeparateXYZ_001, 1);
		_Math_005.addInput(new armory.logicnode.FloatNode(this, -40.0), 0);
		_Math_005.addOutputs([_CanvasSetLocation_003]);
		_CanvasSetLocation_003.addInput(_Math_005, 0);
		_CanvasSetLocation_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_Math_004.addOutputs([_CanvasSetLocation_002, _CanvasSetLocation_003]);
		_SeparateXYZ_001.addOutputs([_Math, _CanvasSetLocation_001, _Math_004]);
		var _Math_001 = new armory.logicnode.MathNode(this);
		_Math_001.property0 = "Add";
		_Math_001.property1 = "false";
		_Math_001.addInput(_SeparateXYZ_001, 1);
		_Math_001.addInput(new armory.logicnode.FloatNode(this, -90.0), 0);
		_Math_001.addOutputs([_CanvasSetLocation]);
		_SeparateXYZ_001.addOutputs([_Math_001, _Math_003, _Math_002, _Math_005]);
		_SeparateXYZ_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Math.addInput(_SeparateXYZ_001, 0);
		_Math.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Math.addOutputs([_CanvasSetLocation]);
		_CanvasSetLocation.addInput(_Math, 0);
		_CanvasSetLocation.addInput(_Math_001, 0);
		_CanvasSetLocation.addOutputs([new armory.logicnode.NullNode(this)]);
		_OnUpdate_003.addOutputs([_CanvasSetLocation, _CanvasSetLocation_002, _CanvasSetLocation_001, _Gate, _CanvasSetLocation_003]);
		_Gate.addInput(_OnUpdate_003, 0);
		_Gate.addInput(_Object_003, 0);
		_Gate.addInput(_PickObject_002, 0);
		var _CanvasSetVisible_005 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_005.addInput(_Gate, 0);
		_CanvasSetVisible_005.addInput(new armory.logicnode.StringNode(this, "Objektbeschriftung"), 0);
		_CanvasSetVisible_005.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		var _CanvasSetVisible_001 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_001.addInput(_CanvasSetVisible_005, 0);
		_CanvasSetVisible_001.addInput(new armory.logicnode.StringNode(this, "erste"), 0);
		_CanvasSetVisible_001.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		var _CanvasSetVisible_006 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_006.addInput(_CanvasSetVisible_001, 0);
		_CanvasSetVisible_006.addInput(new armory.logicnode.StringNode(this, "zweite"), 0);
		_CanvasSetVisible_006.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		var _CanvasSetVisible_003 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_003.addInput(_CanvasSetVisible_006, 0);
		_CanvasSetVisible_003.addInput(new armory.logicnode.StringNode(this, "Linie"), 0);
		_CanvasSetVisible_003.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_CanvasSetVisible_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_CanvasSetVisible_006.addOutputs([_CanvasSetVisible_003]);
		_CanvasSetVisible_001.addOutputs([_CanvasSetVisible_006]);
		_CanvasSetVisible_005.addOutputs([_CanvasSetVisible_001]);
		_Gate.addOutputs([_CanvasSetVisible_005]);
		var _CanvasSetVisible_004 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_004.addInput(_Gate, 1);
		_CanvasSetVisible_004.addInput(new armory.logicnode.StringNode(this, "Objektbeschriftung"), 0);
		_CanvasSetVisible_004.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _CanvasSetVisible = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible.addInput(_CanvasSetVisible_004, 0);
		_CanvasSetVisible.addInput(new armory.logicnode.StringNode(this, "erste"), 0);
		_CanvasSetVisible.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _CanvasSetVisible_007 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_007.addInput(_CanvasSetVisible, 0);
		_CanvasSetVisible_007.addInput(new armory.logicnode.StringNode(this, "zweite"), 0);
		_CanvasSetVisible_007.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		var _CanvasSetVisible_002 = new armory.logicnode.CanvasSetVisibleNode(this);
		_CanvasSetVisible_002.addInput(_CanvasSetVisible_007, 0);
		_CanvasSetVisible_002.addInput(new armory.logicnode.StringNode(this, "Linie"), 0);
		_CanvasSetVisible_002.addInput(new armory.logicnode.BooleanNode(this, true), 0);
		_CanvasSetVisible_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_CanvasSetVisible_007.addOutputs([_CanvasSetVisible_002]);
		_CanvasSetVisible.addOutputs([_CanvasSetVisible_007]);
		_CanvasSetVisible_004.addOutputs([_CanvasSetVisible]);
		_Gate.addOutputs([_CanvasSetVisible_004]);
		_Object_003.addOutputs([_Gate_004, _Gate_005, _Gate_006, _Gate]);
		_Gate_004.addInput(_Object_003, 0);
		_Gate_004.addInput(_PickObject_002, 0);
		_Gate_004.addOutputs([_Gate_016]);
		_Gate_016.addInput(_Gate_004, 0);
		_Gate_016.addInput(_Math_012, 0);
		var _Float_006 = new armory.logicnode.FloatNode(this);
		_Float_006.addInput(new armory.logicnode.FloatNode(this, -200.0), 0);
		_Float_006.addOutputs([_Gate_016]);
		_Gate_016.addInput(_Float_006, 0);
		var _Gate_015 = new armory.logicnode.GateNode(this);
		_Gate_015.property0 = "Less Equal";
		_Gate_015.property1 = 9.999999747378752e-05;
		_Gate_015.addInput(_Gate_016, 0);
		_Gate_015.addInput(_Math_012, 0);
		var _Float_007 = new armory.logicnode.FloatNode(this);
		_Float_007.addInput(new armory.logicnode.FloatNode(this, 20.0), 0);
		_Float_007.addOutputs([_Gate_015]);
		_Gate_015.addInput(_Float_007, 0);
		var _TranslateObject = new armory.logicnode.TranslateObjectNode(this);
		_TranslateObject.addInput(_Gate_015, 0);
		_TranslateObject.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_TranslateObject.addInput(_VectorMath, 0);
		_TranslateObject.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_TranslateObject.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_015.addOutputs([_TranslateObject]);
		_Gate_016.addOutputs([_Gate_015]);
		_Math_012.addOutputs([_Gate_016, _Gate_015]);
		_SeparateXYZ_010.addOutputs([_Math_012]);
		_SeparateXYZ_010.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_010.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_VectorMath.addOutputs([_SeparateXYZ_010, _TranslateObject]);
		_VectorMath.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_MouseCoords_002.addOutputs([_VectorMath, _SeparateXYZ_006, _SeparateXYZ_007]);
		var _Vector_009 = new armory.logicnode.VectorNode(this);
		_Vector_009.addInput(_MouseCoords_002, 2);
		_Vector_009.addInput(new armory.logicnode.FloatNode(this, 1.0), 0);
		_Vector_009.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		var _VectorMath_002 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_002.property0 = "Multiply";
		_VectorMath_002.addInput(_Vector_009, 0);
		_VectorMath_002.addInput(new armory.logicnode.VectorNode(this, 5.0, 5.0, 5.0), 0);
		var _TranslateObject_002 = new armory.logicnode.TranslateObjectNode(this);
		_TranslateObject_002.addInput(_Gate_007, 0);
		_TranslateObject_002.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_TranslateObject_002.addInput(_VectorMath_002, 0);
		_TranslateObject_002.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_TranslateObject_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_VectorMath_002.addOutputs([_TranslateObject_002]);
		_VectorMath_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Vector_009.addOutputs([_VectorMath_002]);
		_MouseCoords_002.addOutputs([_Vector_009, _Math_011]);
		_PickObject_002.addInput(_MouseCoords_002, 0);
		_PickObject_002.addOutputs([_Gate_004, _Gate_005, _Gate_006, _Gate_007, _Gate]);
		_PickObject_002.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_Gate_007.addInput(_PickObject_002, 0);
		var _Object_002 = new armory.logicnode.ObjectNode(this);
		_Object_002.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_Object_002.addOutputs([_Gate_007, _SetTransform_001]);
		_Gate_007.addInput(_Object_002, 0);
		_Gate_007.addOutputs([_TranslateObject_002]);
		var _SetLightStrength = new armory.logicnode.SetLightStrengthNode(this);
		_SetLightStrength.addInput(_OnUpdate_002, 0);
		_SetLightStrength.addInput(new armory.logicnode.ObjectNode(this, "Spot.004"), 0);
		var _SeparateXYZ_002 = new armory.logicnode.SeparateVectorNode(this);
		var _VectorMath_003 = new armory.logicnode.VectorMathNode(this);
		_VectorMath_003.property0 = "Multiply";
		var _GetLocation_001 = new armory.logicnode.GetLocationNode(this);
		_GetLocation_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetLocation_001.addOutputs([_VectorMath_003]);
		_VectorMath_003.addInput(_GetLocation_001, 0);
		_VectorMath_003.addInput(new armory.logicnode.VectorNode(this, 1000.0, 1000.0, 1000.0), 0);
		_VectorMath_003.addOutputs([_SeparateXYZ_002]);
		_VectorMath_003.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_002.addInput(_VectorMath_003, 0);
		var _SetLightStrength_001 = new armory.logicnode.SetLightStrengthNode(this);
		_SetLightStrength_001.addInput(_OnUpdate_002, 0);
		_SetLightStrength_001.addInput(new armory.logicnode.ObjectNode(this, "Spot.005"), 0);
		_SetLightStrength_001.addInput(_SeparateXYZ_002, 0);
		_SetLightStrength_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetLightStrength_003 = new armory.logicnode.SetLightStrengthNode(this);
		_SetLightStrength_003.addInput(_OnUpdate_002, 0);
		_SetLightStrength_003.addInput(new armory.logicnode.ObjectNode(this, "Spot.006"), 0);
		_SetLightStrength_003.addInput(_SeparateXYZ_002, 0);
		_SetLightStrength_003.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetLightStrength_002 = new armory.logicnode.SetLightStrengthNode(this);
		_SetLightStrength_002.addInput(_OnUpdate_002, 0);
		_SetLightStrength_002.addInput(new armory.logicnode.ObjectNode(this, "Spot.007"), 0);
		_SetLightStrength_002.addInput(_SeparateXYZ_002, 0);
		_SetLightStrength_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_SeparateXYZ_002.addOutputs([_SetLightStrength, _SetLightStrength_001, _SetLightStrength_003, _SetLightStrength_002]);
		_SeparateXYZ_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SetLightStrength.addInput(_SeparateXYZ_002, 0);
		_SetLightStrength.addOutputs([new armory.logicnode.NullNode(this)]);
		_OnUpdate_002.addOutputs([_Gate_007, _SetTransform_001, _SetLightStrength, _SetLightStrength_001, _SetLightStrength_002, _SetLightStrength_003]);
		_SetTransform_001.addInput(_OnUpdate_002, 0);
		_SetTransform_001.addInput(_Object_002, 0);
		var _GetTransform_001 = new armory.logicnode.GetTransformNode(this);
		_GetTransform_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetTransform_001.addOutputs([_SetTransform_001]);
		_SetTransform_001.addInput(_GetTransform_001, 0);
		_SetTransform_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_001 = new armory.logicnode.SetPropertyNode(this);
		var _OnMouse_003 = new armory.logicnode.OnMouseNode(this);
		_OnMouse_003.property0 = "Released";
		_OnMouse_003.property1 = "left";
		_OnMouse_003.addOutputs([_SetProperty_001]);
		_SetProperty_001.addInput(_OnMouse_003, 0);
		_SetProperty_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetProperty_001.addInput(new armory.logicnode.StringNode(this, "Maus"), 0);
		var _String_001 = new armory.logicnode.StringNode(this);
		_String_001.addInput(new armory.logicnode.StringNode(this, "Aus"), 0);
		_String_001.addOutputs([_SetProperty_001]);
		_SetProperty_001.addInput(_String_001, 0);
		_SetProperty_001.addOutputs([new armory.logicnode.NullNode(this)]);
	}
}