package arm.node;

@:keep class AA_Kamera_Bewegung_001 extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		name = "AA_Kamera_Bewegung_001";
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _TranslateObject = new armory.logicnode.TranslateObjectNode(this);
		var _Gate_015 = new armory.logicnode.GateNode(this);
		_Gate_015.property0 = "Less Equal";
		_Gate_015.property1 = 9.999999747378752e-05;
		var _Gate_016 = new armory.logicnode.GateNode(this);
		_Gate_016.property0 = "Greater Equal";
		_Gate_016.property1 = 9.999999747378752e-05;
		var _OnEvent_001 = new armory.logicnode.OnEventNode(this);
		_OnEvent_001.property0 = "beweg_welt";
		_OnEvent_001.addOutputs([_Gate_016]);
		_Gate_016.addInput(_OnEvent_001, 0);
		var _Math_012 = new armory.logicnode.MathNode(this);
		_Math_012.property0 = "Add";
		_Math_012.property1 = "false";
		var _SeparateXYZ_008 = new armory.logicnode.SeparateVectorNode(this);
		var _GetLocation = new armory.logicnode.GetLocationNode(this);
		_GetLocation.addInput(new armory.logicnode.ObjectNode(this, "Ansicht_side"), 0);
		_GetLocation.addOutputs([_SeparateXYZ_008]);
		_SeparateXYZ_008.addInput(_GetLocation, 0);
		_SeparateXYZ_008.addOutputs([_Math_012]);
		_SeparateXYZ_008.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_008.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Math_012.addInput(_SeparateXYZ_008, 0);
		var _SeparateXYZ_010 = new armory.logicnode.SeparateVectorNode(this);
		var _VectorMath = new armory.logicnode.VectorMathNode(this);
		_VectorMath.property0 = "Multiply";
		var _MouseCoords_004 = new armory.logicnode.MouseCoordsNode(this);
		_MouseCoords_004.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_MouseCoords_004.addOutputs([_VectorMath]);
		_MouseCoords_004.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_VectorMath.addInput(_MouseCoords_004, 1);
		_VectorMath.addInput(new armory.logicnode.VectorNode(this, 0.05000000074505806, 0.0, 0.0), 0);
		_VectorMath.addOutputs([_SeparateXYZ_010, _TranslateObject]);
		_VectorMath.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_010.addInput(_VectorMath, 0);
		_SeparateXYZ_010.addOutputs([_Math_012]);
		_SeparateXYZ_010.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_010.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Math_012.addInput(_SeparateXYZ_010, 0);
		_Math_012.addOutputs([_Gate_016, _Gate_015]);
		_Gate_016.addInput(_Math_012, 0);
		var _Float_006 = new armory.logicnode.FloatNode(this);
		_Float_006.addInput(new armory.logicnode.FloatNode(this, -20.0), 0);
		_Float_006.addOutputs([_Gate_016]);
		_Gate_016.addInput(_Float_006, 0);
		_Gate_016.addOutputs([_Gate_015]);
		_Gate_015.addInput(_Gate_016, 0);
		_Gate_015.addInput(_Math_012, 0);
		var _Float_007 = new armory.logicnode.FloatNode(this);
		_Float_007.addInput(new armory.logicnode.FloatNode(this, 20.0), 0);
		_Float_007.addOutputs([_Gate_015]);
		_Gate_015.addInput(_Float_007, 0);
		_Gate_015.addOutputs([_TranslateObject]);
		_TranslateObject.addInput(_Gate_015, 0);
		_TranslateObject.addInput(new armory.logicnode.ObjectNode(this, "Ansicht_side"), 0);
		_TranslateObject.addInput(_VectorMath, 0);
		_TranslateObject.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_TranslateObject.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty = new armory.logicnode.SetPropertyNode(this);
		var _OnEvent_003 = new armory.logicnode.OnEventNode(this);
		_OnEvent_003.property0 = "dreh_welt_started";
		_OnEvent_003.addOutputs([_SetProperty]);
		_SetProperty.addInput(_OnEvent_003, 0);
		_SetProperty.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetProperty.addInput(new armory.logicnode.StringNode(this, "Maus"), 0);
		var _String = new armory.logicnode.StringNode(this);
		_String.addInput(new armory.logicnode.StringNode(this, "An"), 0);
		var _Gate_008 = new armory.logicnode.GateNode(this);
		_Gate_008.property0 = "Equal";
		_Gate_008.property1 = 9.999999747378752e-05;
		var _OnEvent_004 = new armory.logicnode.OnEventNode(this);
		_OnEvent_004.property0 = "dreh_welt_down";
		_OnEvent_004.addOutputs([_Gate_008]);
		_Gate_008.addInput(_OnEvent_004, 0);
		_Gate_008.addInput(_String, 0);
		var _GetProperty = new armory.logicnode.GetPropertyNode(this);
		_GetProperty.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetProperty.addInput(new armory.logicnode.StringNode(this, "Maus"), 0);
		_GetProperty.addOutputs([_Gate_008]);
		_GetProperty.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Gate_008.addInput(_GetProperty, 0);
		var _Gate_009 = new armory.logicnode.GateNode(this);
		_Gate_009.property0 = "Greater Equal";
		_Gate_009.property1 = 9.999999747378752e-05;
		_Gate_009.addInput(_Gate_008, 0);
		var _Math_009 = new armory.logicnode.MathNode(this);
		_Math_009.property0 = "Add";
		_Math_009.property1 = "false";
		var _SeparateXYZ_009 = new armory.logicnode.SeparateVectorNode(this);
		var _GetRotation_001 = new armory.logicnode.GetRotationNode(this);
		_GetRotation_001.addInput(new armory.logicnode.ObjectNode(this, "Ansicht_up"), 0);
		_GetRotation_001.addOutputs([_SeparateXYZ_009]);
		_GetRotation_001.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_GetRotation_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_GetRotation_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_GetRotation_001.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_GetRotation_001.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_009.addInput(_GetRotation_001, 0);
		_SeparateXYZ_009.addOutputs([_Math_009]);
		_SeparateXYZ_009.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_009.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Math_009.addInput(_SeparateXYZ_009, 0);
		var _Math_008 = new armory.logicnode.MathNode(this);
		_Math_008.property0 = "Multiply";
		_Math_008.property1 = "false";
		var _SeparateXYZ_007 = new armory.logicnode.SeparateVectorNode(this);
		var _MouseCoords_002 = new armory.logicnode.MouseCoordsNode(this);
		_MouseCoords_002.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		var _SeparateXYZ_006 = new armory.logicnode.SeparateVectorNode(this);
		_SeparateXYZ_006.addInput(_MouseCoords_002, 1);
		var _Math_007 = new armory.logicnode.MathNode(this);
		_Math_007.property0 = "Multiply";
		_Math_007.property1 = "false";
		_Math_007.addInput(_SeparateXYZ_006, 0);
		_Math_007.addInput(new armory.logicnode.FloatNode(this, -0.004999999888241291), 0);
		var _Vector = new armory.logicnode.VectorNode(this);
		_Vector.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector.addInput(_Math_007, 0);
		var _RotateObject = new armory.logicnode.RotateObjectNode(this);
		var _Gate_012 = new armory.logicnode.GateNode(this);
		_Gate_012.property0 = "Less Equal";
		_Gate_012.property1 = 9.999999747378752e-05;
		var _Gate_011 = new armory.logicnode.GateNode(this);
		_Gate_011.property0 = "Greater Equal";
		_Gate_011.property1 = 9.999999747378752e-05;
		_Gate_011.addInput(_Gate_008, 0);
		var _Math_010 = new armory.logicnode.MathNode(this);
		_Math_010.property0 = "Add";
		_Math_010.property1 = "false";
		var _SeparateXYZ_011 = new armory.logicnode.SeparateVectorNode(this);
		var _GetRotation_002 = new armory.logicnode.GetRotationNode(this);
		_GetRotation_002.addInput(new armory.logicnode.ObjectNode(this, "Ansicht_side"), 0);
		_GetRotation_002.addOutputs([_SeparateXYZ_011]);
		_GetRotation_002.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_GetRotation_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_GetRotation_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_GetRotation_002.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_GetRotation_002.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_011.addInput(_GetRotation_002, 0);
		_SeparateXYZ_011.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_011.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_011.addOutputs([_Math_010]);
		_Math_010.addInput(_SeparateXYZ_011, 2);
		_Math_010.addInput(_Math_007, 0);
		_Math_010.addOutputs([_Gate_011, _Gate_012]);
		_Gate_011.addInput(_Math_010, 0);
		var _Float_002 = new armory.logicnode.FloatNode(this);
		_Float_002.addInput(new armory.logicnode.FloatNode(this, -1.2999999523162842), 0);
		_Float_002.addOutputs([_Gate_011]);
		_Gate_011.addInput(_Float_002, 0);
		_Gate_011.addOutputs([_Gate_012]);
		_Gate_012.addInput(_Gate_011, 0);
		_Gate_012.addInput(_Math_010, 0);
		var _Float_003 = new armory.logicnode.FloatNode(this);
		_Float_003.addInput(new armory.logicnode.FloatNode(this, 1.2999999523162842), 0);
		_Float_003.addOutputs([_Gate_012]);
		_Gate_012.addInput(_Float_003, 0);
		_Gate_012.addOutputs([_RotateObject]);
		_RotateObject.addInput(_Gate_012, 0);
		_RotateObject.addInput(new armory.logicnode.ObjectNode(this, "Ansicht_side"), 0);
		_RotateObject.addInput(_Vector, 0);
		_RotateObject.addOutputs([new armory.logicnode.NullNode(this)]);
		_Vector.addOutputs([_RotateObject]);
		_Math_007.addOutputs([_Vector, _Math_010]);
		_SeparateXYZ_006.addOutputs([_Math_007]);
		_SeparateXYZ_006.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_006.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_MouseCoords_002.addOutputs([_SeparateXYZ_006, _SeparateXYZ_007]);
		_MouseCoords_002.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_SeparateXYZ_007.addInput(_MouseCoords_002, 1);
		_SeparateXYZ_007.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_SeparateXYZ_007.addOutputs([_Math_008]);
		_SeparateXYZ_007.addOutputs([new armory.logicnode.FloatNode(this, 0.0)]);
		_Math_008.addInput(_SeparateXYZ_007, 1);
		_Math_008.addInput(new armory.logicnode.FloatNode(this, 0.004999999888241291), 0);
		var _Vector_001 = new armory.logicnode.VectorNode(this);
		_Vector_001.addInput(_Math_008, 0);
		_Vector_001.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_001.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		var _RotateObject_001 = new armory.logicnode.RotateObjectNode(this);
		var _Gate_010 = new armory.logicnode.GateNode(this);
		_Gate_010.property0 = "Less Equal";
		_Gate_010.property1 = 9.999999747378752e-05;
		_Gate_010.addInput(_Gate_009, 0);
		_Gate_010.addInput(_Math_009, 0);
		var _Float_001 = new armory.logicnode.FloatNode(this);
		_Float_001.addInput(new armory.logicnode.FloatNode(this, 1.570796012878418), 0);
		_Float_001.addOutputs([_Gate_010]);
		_Gate_010.addInput(_Float_001, 0);
		_Gate_010.addOutputs([_RotateObject_001]);
		_RotateObject_001.addInput(_Gate_010, 0);
		_RotateObject_001.addInput(new armory.logicnode.ObjectNode(this, "Ansicht_up"), 0);
		_RotateObject_001.addInput(_Vector_001, 0);
		_RotateObject_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Vector_001.addOutputs([_RotateObject_001]);
		_Math_008.addOutputs([_Vector_001, _Math_009]);
		_Math_009.addInput(_Math_008, 0);
		_Math_009.addOutputs([_Gate_009, _Gate_010]);
		_Gate_009.addInput(_Math_009, 0);
		var _Float = new armory.logicnode.FloatNode(this);
		_Float.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Float.addOutputs([_Gate_009]);
		_Gate_009.addInput(_Float, 0);
		_Gate_009.addOutputs([_Gate_010]);
		_Gate_008.addOutputs([_Gate_009, _Gate_011]);
		_String.addOutputs([_SetProperty, _Gate_008]);
		_SetProperty.addInput(_String, 0);
		_SetProperty.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_001 = new armory.logicnode.SetPropertyNode(this);
		var _OnEvent_002 = new armory.logicnode.OnEventNode(this);
		_OnEvent_002.property0 = "dreh_welt_released";
		_OnEvent_002.addOutputs([_SetProperty_001]);
		_SetProperty_001.addInput(_OnEvent_002, 0);
		_SetProperty_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetProperty_001.addInput(new armory.logicnode.StringNode(this, "Maus"), 0);
		var _String_001 = new armory.logicnode.StringNode(this);
		_String_001.addInput(new armory.logicnode.StringNode(this, "Aus"), 0);
		_String_001.addOutputs([_SetProperty_001]);
		_SetProperty_001.addInput(_String_001, 0);
		_SetProperty_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SendGlobalEvent = new armory.logicnode.SendGlobalEventNode(this);
		var _OnUpdate = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate.property0 = "Update";
		_OnUpdate.addOutputs([_SendGlobalEvent]);
		_SendGlobalEvent.addInput(_OnUpdate, 0);
		_SendGlobalEvent.addInput(new armory.logicnode.StringNode(this, "Calc_Beams"), 0);
		_SendGlobalEvent.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetLightStrength_002 = new armory.logicnode.SetLightStrengthNode(this);
		var _ArrayLoop = new armory.logicnode.ArrayLoopNode(this);
		var _Alternate = new armory.logicnode.AlternateNode(this);
		var _OnCanvasElement = new armory.logicnode.OnCanvasElementNode(this);
		_OnCanvasElement.property0 = "click";
		_OnCanvasElement.property1 = "released";
		_OnCanvasElement.property2 = "left";
		_OnCanvasElement.addInput(new armory.logicnode.StringNode(this, "Lichtschalter"), 0);
		_OnCanvasElement.addOutputs([_Alternate]);
		_Alternate.addInput(_OnCanvasElement, 0);
		_Alternate.addOutputs([_ArrayLoop]);
		var _ArrayLoop_001 = new armory.logicnode.ArrayLoopNode(this);
		_ArrayLoop_001.addInput(_Alternate, 1);
		var _Array_Object_ = new armory.logicnode.ArrayObjectNode(this);
		_Array_Object_.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_Array_Object_.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_Array_Object_.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_Array_Object_.addOutputs([_ArrayLoop, _ArrayLoop_001]);
		_Array_Object_.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_ArrayLoop_001.addInput(_Array_Object_, 0);
		var _SetLightStrength_003 = new armory.logicnode.SetLightStrengthNode(this);
		_SetLightStrength_003.addInput(_ArrayLoop_001, 0);
		_SetLightStrength_003.addInput(_ArrayLoop_001, 1);
		_SetLightStrength_003.addInput(new armory.logicnode.FloatNode(this, 40000.0), 0);
		_SetLightStrength_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_ArrayLoop_001.addOutputs([_SetLightStrength_003]);
		_ArrayLoop_001.addOutputs([_SetLightStrength_003]);
		_ArrayLoop_001.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_ArrayLoop_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Alternate.addOutputs([_ArrayLoop_001]);
		_ArrayLoop.addInput(_Alternate, 0);
		_ArrayLoop.addInput(_Array_Object_, 0);
		_ArrayLoop.addOutputs([_SetLightStrength_002]);
		_ArrayLoop.addOutputs([_SetLightStrength_002]);
		_ArrayLoop.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_ArrayLoop.addOutputs([new armory.logicnode.NullNode(this)]);
		_SetLightStrength_002.addInput(_ArrayLoop, 0);
		_SetLightStrength_002.addInput(_ArrayLoop, 1);
		_SetLightStrength_002.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_SetLightStrength_002.addOutputs([new armory.logicnode.NullNode(this)]);
		var _TranslateObject_001 = new armory.logicnode.TranslateObjectNode(this);
		var _Gate_014 = new armory.logicnode.GateNode(this);
		_Gate_014.property0 = "Less Equal";
		_Gate_014.property1 = 9.999999747378752e-05;
		var _Gate_013 = new armory.logicnode.GateNode(this);
		_Gate_013.property0 = "Greater Equal";
		_Gate_013.property1 = 9.999999747378752e-05;
		var _OnEvent = new armory.logicnode.OnEventNode(this);
		_OnEvent.property0 = "dreh_welt";
		_OnEvent.addOutputs([_Gate_013]);
		_Gate_013.addInput(_OnEvent, 0);
		var _Math_006 = new armory.logicnode.MathNode(this);
		_Math_006.property0 = "Add";
		_Math_006.property1 = "false";
		var _GetDistance = new armory.logicnode.GetDistanceNode(this);
		_GetDistance.addInput(new armory.logicnode.ObjectNode(this, "Camera.001"), 0);
		_GetDistance.addInput(new armory.logicnode.ObjectNode(this, "Ansicht_side"), 0);
		_GetDistance.addOutputs([_Math_006]);
		_Math_006.addInput(_GetDistance, 0);
		var _Math_011 = new armory.logicnode.MathNode(this);
		_Math_011.property0 = "Multiply";
		_Math_011.property1 = "false";
		var _MouseCoords_003 = new armory.logicnode.MouseCoordsNode(this);
		_MouseCoords_003.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_MouseCoords_003.addOutputs([new armory.logicnode.VectorNode(this, 0.0, 0.0, 0.0)]);
		_MouseCoords_003.addOutputs([_Math_011]);
		_Math_011.addInput(_MouseCoords_003, 2);
		_Math_011.addInput(new armory.logicnode.FloatNode(this, 4.0), 0);
		var _Vector_003 = new armory.logicnode.VectorNode(this);
		_Vector_003.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_003.addInput(_Math_011, 0);
		_Vector_003.addInput(new armory.logicnode.FloatNode(this, 0.0), 0);
		_Vector_003.addOutputs([_TranslateObject_001]);
		_Math_011.addOutputs([_Vector_003, _Math_006]);
		_Math_006.addInput(_Math_011, 0);
		_Math_006.addOutputs([_Gate_013, _Gate_014]);
		_Gate_013.addInput(_Math_006, 0);
		var _Float_004 = new armory.logicnode.FloatNode(this);
		_Float_004.addInput(new armory.logicnode.FloatNode(this, 50.0), 0);
		_Float_004.addOutputs([_Gate_013]);
		_Gate_013.addInput(_Float_004, 0);
		_Gate_013.addOutputs([_Gate_014]);
		_Gate_014.addInput(_Gate_013, 0);
		_Gate_014.addInput(_Math_006, 0);
		var _Float_005 = new armory.logicnode.FloatNode(this);
		_Float_005.addInput(new armory.logicnode.FloatNode(this, 200.0), 0);
		_Float_005.addOutputs([_Gate_014]);
		_Gate_014.addInput(_Float_005, 0);
		_Gate_014.addOutputs([_TranslateObject_001]);
		_TranslateObject_001.addInput(_Gate_014, 0);
		_TranslateObject_001.addInput(new armory.logicnode.ObjectNode(this, "Camera.001"), 0);
		_TranslateObject_001.addInput(_Vector_003, 0);
		_TranslateObject_001.addInput(new armory.logicnode.BooleanNode(this, false), 0);
		_TranslateObject_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_008 = new armory.logicnode.SetPropertyNode(this);
		var _OnInit_002 = new armory.logicnode.OnInitNode(this);
		_OnInit_002.addOutputs([_SetProperty_008]);
		_SetProperty_008.addInput(_OnInit_002, 0);
		_SetProperty_008.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetProperty_008.addInput(new armory.logicnode.StringNode(this, "lock_komponent"), 0);
		var _Integer_014 = new armory.logicnode.IntegerNode(this);
		_Integer_014.addInput(new armory.logicnode.IntegerNode(this, 0), 0);
		var _SetProperty_007 = new armory.logicnode.SetPropertyNode(this);
		var _OnKeyboard_003 = new armory.logicnode.OnKeyboardNode(this);
		_OnKeyboard_003.property0 = "Released";
		_OnKeyboard_003.property1 = "alt";
		_OnKeyboard_003.addOutputs([_SetProperty_007]);
		_SetProperty_007.addInput(_OnKeyboard_003, 0);
		_SetProperty_007.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetProperty_007.addInput(new armory.logicnode.StringNode(this, "lock_komponent"), 0);
		_SetProperty_007.addInput(_Integer_014, 0);
		_SetProperty_007.addOutputs([new armory.logicnode.NullNode(this)]);
		_Integer_014.addOutputs([_SetProperty_007, _SetProperty_008]);
		_SetProperty_008.addInput(_Integer_014, 0);
		_SetProperty_008.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_006 = new armory.logicnode.SetPropertyNode(this);
		var _OnKeyboard_002 = new armory.logicnode.OnKeyboardNode(this);
		_OnKeyboard_002.property0 = "Down";
		_OnKeyboard_002.property1 = "alt";
		_OnKeyboard_002.addOutputs([_SetProperty_006]);
		_SetProperty_006.addInput(_OnKeyboard_002, 0);
		_SetProperty_006.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_SetProperty_006.addInput(new armory.logicnode.StringNode(this, "lock_komponent"), 0);
		var _Integer_013 = new armory.logicnode.IntegerNode(this);
		_Integer_013.addInput(new armory.logicnode.IntegerNode(this, 1), 0);
		_Integer_013.addOutputs([_SetProperty_006]);
		_SetProperty_006.addInput(_Integer_013, 0);
		_SetProperty_006.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SendGlobalEvent_005 = new armory.logicnode.SendGlobalEventNode(this);
		var _Gate_022 = new armory.logicnode.GateNode(this);
		_Gate_022.property0 = "Equal";
		_Gate_022.property1 = 9.999999747378752e-05;
		var _OnUpdate_004 = new armory.logicnode.OnUpdateNode(this);
		_OnUpdate_004.property0 = "Update";
		_OnUpdate_004.addOutputs([_Gate_022]);
		_Gate_022.addInput(_OnUpdate_004, 0);
		var _GetProperty_012 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_012.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetProperty_012.addInput(new armory.logicnode.StringNode(this, "lock_komponent"), 0);
		var _Gate_025 = new armory.logicnode.GateNode(this);
		_Gate_025.property0 = "Equal";
		_Gate_025.property1 = 9.999999747378752e-05;
		var _OnMouse_006 = new armory.logicnode.OnMouseNode(this);
		_OnMouse_006.property0 = "Released";
		_OnMouse_006.property1 = "left";
		_OnMouse_006.addOutputs([_Gate_025]);
		_Gate_025.addInput(_OnMouse_006, 0);
		_Gate_025.addInput(_GetProperty_012, 0);
		var _Integer_012 = new armory.logicnode.IntegerNode(this);
		_Integer_012.addInput(new armory.logicnode.IntegerNode(this, 1), 0);
		var _Gate_024 = new armory.logicnode.GateNode(this);
		_Gate_024.property0 = "Equal";
		_Gate_024.property1 = 9.999999747378752e-05;
		var _OnMouse_005 = new armory.logicnode.OnMouseNode(this);
		_OnMouse_005.property0 = "Started";
		_OnMouse_005.property1 = "left";
		_OnMouse_005.addOutputs([_Gate_024]);
		_Gate_024.addInput(_OnMouse_005, 0);
		_Gate_024.addInput(_GetProperty_012, 0);
		_Gate_024.addInput(_Integer_012, 0);
		var _SendGlobalEvent_003 = new armory.logicnode.SendGlobalEventNode(this);
		_SendGlobalEvent_003.addInput(_Gate_024, 0);
		_SendGlobalEvent_003.addInput(new armory.logicnode.StringNode(this, "beweg_komponent_started"), 0);
		_SendGlobalEvent_003.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_024.addOutputs([_SendGlobalEvent_003]);
		var _SendGlobalEvent_008 = new armory.logicnode.SendGlobalEventNode(this);
		_SendGlobalEvent_008.addInput(_Gate_024, 1);
		_SendGlobalEvent_008.addInput(new armory.logicnode.StringNode(this, "dreh_welt_started"), 0);
		_SendGlobalEvent_008.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_024.addOutputs([_SendGlobalEvent_008]);
		var _Gate_023 = new armory.logicnode.GateNode(this);
		_Gate_023.property0 = "Equal";
		_Gate_023.property1 = 9.999999747378752e-05;
		var _OnMouse_007 = new armory.logicnode.OnMouseNode(this);
		_OnMouse_007.property0 = "Down";
		_OnMouse_007.property1 = "left";
		_OnMouse_007.addOutputs([_Gate_023]);
		_Gate_023.addInput(_OnMouse_007, 0);
		_Gate_023.addInput(_GetProperty_012, 0);
		_Gate_023.addInput(_Integer_012, 0);
		var _SendGlobalEvent_004 = new armory.logicnode.SendGlobalEventNode(this);
		_SendGlobalEvent_004.addInput(_Gate_023, 0);
		_SendGlobalEvent_004.addInput(new armory.logicnode.StringNode(this, "beweg_komponent_down"), 0);
		_SendGlobalEvent_004.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_023.addOutputs([_SendGlobalEvent_004]);
		var _SendGlobalEvent_009 = new armory.logicnode.SendGlobalEventNode(this);
		_SendGlobalEvent_009.addInput(_Gate_023, 1);
		_SendGlobalEvent_009.addInput(new armory.logicnode.StringNode(this, "dreh_welt_down"), 0);
		_SendGlobalEvent_009.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_023.addOutputs([_SendGlobalEvent_009]);
		var _Gate_027 = new armory.logicnode.GateNode(this);
		_Gate_027.property0 = "Equal";
		_Gate_027.property1 = 9.999999747378752e-05;
		var _OnMouse_004 = new armory.logicnode.OnMouseNode(this);
		_OnMouse_004.property0 = "Down";
		_OnMouse_004.property1 = "middle";
		_OnMouse_004.addOutputs([_Gate_027]);
		_Gate_027.addInput(_OnMouse_004, 0);
		_Gate_027.addInput(_GetProperty_012, 0);
		_Gate_027.addInput(_Integer_012, 0);
		_Gate_027.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SendGlobalEvent_006 = new armory.logicnode.SendGlobalEventNode(this);
		_SendGlobalEvent_006.addInput(_Gate_027, 1);
		_SendGlobalEvent_006.addInput(new armory.logicnode.StringNode(this, "beweg_welt"), 0);
		_SendGlobalEvent_006.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_027.addOutputs([_SendGlobalEvent_006]);
		_Integer_012.addOutputs([_Gate_022, _Gate_025, _Gate_024, _Gate_023, _Gate_027]);
		_Gate_025.addInput(_Integer_012, 0);
		var _SendGlobalEvent_002 = new armory.logicnode.SendGlobalEventNode(this);
		_SendGlobalEvent_002.addInput(_Gate_025, 0);
		_SendGlobalEvent_002.addInput(new armory.logicnode.StringNode(this, "beweg_komponent_released"), 0);
		_SendGlobalEvent_002.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_025.addOutputs([_SendGlobalEvent_002]);
		var _SendGlobalEvent_007 = new armory.logicnode.SendGlobalEventNode(this);
		_SendGlobalEvent_007.addInput(_Gate_025, 1);
		_SendGlobalEvent_007.addInput(new armory.logicnode.StringNode(this, "dreh_welt_released"), 0);
		_SendGlobalEvent_007.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_025.addOutputs([_SendGlobalEvent_007]);
		_GetProperty_012.addOutputs([_Gate_022, _Gate_025, _Gate_024, _Gate_023, _Gate_027]);
		_GetProperty_012.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Gate_022.addInput(_GetProperty_012, 0);
		_Gate_022.addInput(_Integer_012, 0);
		var _SendGlobalEvent_001 = new armory.logicnode.SendGlobalEventNode(this);
		_SendGlobalEvent_001.addInput(_Gate_022, 0);
		_SendGlobalEvent_001.addInput(new armory.logicnode.StringNode(this, "dreh_komponent"), 0);
		_SendGlobalEvent_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_Gate_022.addOutputs([_SendGlobalEvent_001]);
		_Gate_022.addOutputs([_SendGlobalEvent_005]);
		_SendGlobalEvent_005.addInput(_Gate_022, 1);
		_SendGlobalEvent_005.addInput(new armory.logicnode.StringNode(this, "dreh_welt"), 0);
		_SendGlobalEvent_005.addOutputs([new armory.logicnode.NullNode(this)]);
	}
}