package arm.node;

@:keep class ServerTest extends armory.logicnode.LogicTree {

	var functionNodes:Map<String, armory.logicnode.FunctionNode>;

	var functionOutputNodes:Map<String, armory.logicnode.FunctionOutputNode>;

	public function new() {
		super();
		name = "ServerTest";
		this.functionNodes = new Map();
		this.functionOutputNodes = new Map();
		notifyOnAdd(add);
	}

	override public function add() {
		var _Print_008 = new armory.logicnode.PrintNode(this);
		var _Print_006 = new armory.logicnode.PrintNode(this);
		var _Print_005 = new armory.logicnode.PrintNode(this);
		var _Print_003 = new armory.logicnode.PrintNode(this);
		var _Print_001 = new armory.logicnode.PrintNode(this);
		var _Print = new armory.logicnode.PrintNode(this);
		_Print.addInput(new armory.logicnode.NullNode(this), 0);
		_Print.addInput(new armory.logicnode.StringNode(this, "inputAngle1:"), 0);
		_Print.addOutputs([_Print_001]);
		_Print_001.addInput(_Print, 0);
		var _GetProperty = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject = new armory.logicnode.GlobalObjectNode(this);
		var _GetProperty_001 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_001.addInput(_GlobalObject, 0);
		_GetProperty_001.addInput(new armory.logicnode.StringNode(this, "inputAngle2"), 0);
		_GetProperty_001.addOutputs([_Print_005]);
		_GetProperty_001.addOutputs([new armory.logicnode.StringNode(this, "")]);
		var _GetProperty_002 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_002.addInput(_GlobalObject, 0);
		_GetProperty_002.addInput(new armory.logicnode.StringNode(this, "inputAngle3"), 0);
		_GetProperty_002.addOutputs([_Print_008]);
		_GetProperty_002.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_GlobalObject.addOutputs([_GetProperty, _GetProperty_001, _GetProperty_002]);
		_GetProperty.addInput(_GlobalObject, 0);
		_GetProperty.addInput(new armory.logicnode.StringNode(this, "inputAngle1"), 0);
		_GetProperty.addOutputs([_Print_001]);
		_GetProperty.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Print_001.addInput(_GetProperty, 0);
		_Print_001.addOutputs([_Print_003]);
		_Print_003.addInput(_Print_001, 0);
		_Print_003.addInput(new armory.logicnode.StringNode(this, "inputAngle1:"), 0);
		_Print_003.addOutputs([_Print_005]);
		_Print_005.addInput(_Print_003, 0);
		_Print_005.addInput(_GetProperty_001, 0);
		_Print_005.addOutputs([_Print_006]);
		_Print_006.addInput(_Print_005, 0);
		_Print_006.addInput(new armory.logicnode.StringNode(this, "inputAngle1:"), 0);
		_Print_006.addOutputs([_Print_008]);
		_Print_008.addInput(_Print_006, 0);
		_Print_008.addInput(_GetProperty_002, 0);
		_Print_008.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Print_013 = new armory.logicnode.PrintNode(this);
		var _Print_017 = new armory.logicnode.PrintNode(this);
		var _Print_016 = new armory.logicnode.PrintNode(this);
		var _Print_018 = new armory.logicnode.PrintNode(this);
		var _Print_015 = new armory.logicnode.PrintNode(this);
		var _Print_004 = new armory.logicnode.PrintNode(this);
		_Print_004.addInput(new armory.logicnode.NullNode(this), 0);
		_Print_004.addInput(new armory.logicnode.StringNode(this, "inputC1"), 0);
		_Print_004.addOutputs([_Print_015]);
		_Print_015.addInput(_Print_004, 0);
		var _GetProperty_004 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_002 = new armory.logicnode.GlobalObjectNode(this);
		var _GetProperty_007 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_007.addInput(_GlobalObject_002, 0);
		_GetProperty_007.addInput(new armory.logicnode.StringNode(this, "inputC2"), 0);
		_GetProperty_007.addOutputs([_Print_016]);
		_GetProperty_007.addOutputs([new armory.logicnode.StringNode(this, "")]);
		var _GetProperty_006 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_006.addInput(_GlobalObject_002, 0);
		_GetProperty_006.addInput(new armory.logicnode.StringNode(this, "inputCC"), 0);
		_GetProperty_006.addOutputs([_Print_013]);
		_GetProperty_006.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_GlobalObject_002.addOutputs([_GetProperty_004, _GetProperty_007, _GetProperty_006]);
		_GetProperty_004.addInput(_GlobalObject_002, 0);
		_GetProperty_004.addInput(new armory.logicnode.StringNode(this, "inputC1"), 0);
		_GetProperty_004.addOutputs([_Print_015]);
		_GetProperty_004.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Print_015.addInput(_GetProperty_004, 0);
		_Print_015.addOutputs([_Print_018]);
		_Print_018.addInput(_Print_015, 0);
		_Print_018.addInput(new armory.logicnode.StringNode(this, "inputC2"), 0);
		_Print_018.addOutputs([_Print_016]);
		_Print_016.addInput(_Print_018, 0);
		_Print_016.addInput(_GetProperty_007, 0);
		_Print_016.addOutputs([_Print_017]);
		_Print_017.addInput(_Print_016, 0);
		_Print_017.addInput(new armory.logicnode.StringNode(this, "inputCC"), 0);
		_Print_017.addOutputs([_Print_013]);
		_Print_013.addInput(_Print_017, 0);
		_Print_013.addInput(_GetProperty_006, 0);
		_Print_013.addOutputs([new armory.logicnode.NullNode(this)]);
		var _Print_014 = new armory.logicnode.PrintNode(this);
		var _Print_012 = new armory.logicnode.PrintNode(this);
		var _Print_011 = new armory.logicnode.PrintNode(this);
		var _Print_009 = new armory.logicnode.PrintNode(this);
		_Print_009.addInput(new armory.logicnode.NullNode(this), 0);
		_Print_009.addInput(new armory.logicnode.StringNode(this, "inputVolt1"), 0);
		_Print_009.addOutputs([_Print_011]);
		_Print_011.addInput(_Print_009, 0);
		var _GetProperty_003 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_001 = new armory.logicnode.GlobalObjectNode(this);
		var _GetProperty_005 = new armory.logicnode.GetPropertyNode(this);
		_GetProperty_005.addInput(_GlobalObject_001, 0);
		_GetProperty_005.addInput(new armory.logicnode.StringNode(this, "inputVolt2"), 0);
		_GetProperty_005.addOutputs([_Print_014]);
		_GetProperty_005.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_GlobalObject_001.addOutputs([_GetProperty_003, _GetProperty_005]);
		_GetProperty_003.addInput(_GlobalObject_001, 0);
		_GetProperty_003.addInput(new armory.logicnode.StringNode(this, "inputVolt1"), 0);
		_GetProperty_003.addOutputs([_Print_011]);
		_GetProperty_003.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_Print_011.addInput(_GetProperty_003, 0);
		_Print_011.addOutputs([_Print_012]);
		_Print_012.addInput(_Print_011, 0);
		_Print_012.addInput(new armory.logicnode.StringNode(this, "inputVolt2:"), 0);
		_Print_012.addOutputs([_Print_014]);
		_Print_014.addInput(_Print_012, 0);
		_Print_014.addInput(_GetProperty_005, 0);
		_Print_014.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty = new armory.logicnode.SetPropertyNode(this);
		_SetProperty.addInput(new armory.logicnode.NullNode(this), 0);
		var _GlobalObject_003 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_003.addOutputs([_SetProperty]);
		_SetProperty.addInput(_GlobalObject_003, 0);
		_SetProperty.addInput(new armory.logicnode.StringNode(this, "xAxis"), 0);
		var _Array_Float_ = new armory.logicnode.ArrayFloatNode(this);
		_Array_Float_.addOutputs([_SetProperty]);
		_Array_Float_.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_SetProperty.addInput(_Array_Float_, 0);
		_SetProperty.addOutputs([new armory.logicnode.NullNode(this)]);
		var _GetProperty_008 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_005 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_005.addOutputs([_GetProperty_008]);
		_GetProperty_008.addInput(_GlobalObject_005, 0);
		_GetProperty_008.addInput(new armory.logicnode.StringNode(this, "xAxis"), 0);
		_GetProperty_008.addOutputs([new armory.logicnode.NullNode(this)]);
		_GetProperty_008.addOutputs([new armory.logicnode.StringNode(this, "")]);
		var _SetProperty_001 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_001.addInput(new armory.logicnode.NullNode(this), 0);
		var _GlobalObject_004 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_004.addOutputs([_SetProperty_001]);
		_SetProperty_001.addInput(_GlobalObject_004, 0);
		_SetProperty_001.addInput(new armory.logicnode.StringNode(this, "ArrayYAxis"), 0);
		var _Array = new armory.logicnode.ArrayNode(this);
		var _Array_Float__001 = new armory.logicnode.ArrayFloatNode(this);
		_Array_Float__001.addOutputs([_Array]);
		_Array_Float__001.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_Array.addInput(_Array_Float__001, 0);
		var _Array_Float__002 = new armory.logicnode.ArrayFloatNode(this);
		_Array_Float__002.addOutputs([_Array]);
		_Array_Float__002.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_Array.addInput(_Array_Float__002, 0);
		_Array.addInput(new armory.logicnode.NullNode(this), 0);
		_Array.addInput(new armory.logicnode.NullNode(this), 0);
		_Array.addOutputs([_SetProperty_001]);
		_Array.addOutputs([new armory.logicnode.IntegerNode(this, 0)]);
		_SetProperty_001.addInput(_Array, 0);
		_SetProperty_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _ArrayGet_001 = new armory.logicnode.ArrayGetNode(this);
		var _GetProperty_009 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_006 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_006.addOutputs([_GetProperty_009]);
		_GetProperty_009.addInput(_GlobalObject_006, 0);
		_GetProperty_009.addInput(new armory.logicnode.StringNode(this, "ArrayYAxis"), 0);
		var _ArrayGet = new armory.logicnode.ArrayGetNode(this);
		_ArrayGet.addInput(_GetProperty_009, 0);
		_ArrayGet.addInput(new armory.logicnode.IntegerNode(this, 0), 0);
		_ArrayGet.addOutputs([new armory.logicnode.NullNode(this)]);
		_GetProperty_009.addOutputs([_ArrayGet, _ArrayGet_001]);
		_GetProperty_009.addOutputs([new armory.logicnode.StringNode(this, "")]);
		_ArrayGet_001.addInput(_GetProperty_009, 0);
		_ArrayGet_001.addInput(new armory.logicnode.IntegerNode(this, 1), 0);
		_ArrayGet_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_004 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_004.addInput(new armory.logicnode.NullNode(this), 0);
		var _GlobalObject_011 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_011.addOutputs([_SetProperty_004]);
		_SetProperty_004.addInput(_GlobalObject_011, 0);
		_SetProperty_004.addInput(new armory.logicnode.StringNode(this, "Subexercise"), 0);
		var _String_002 = new armory.logicnode.StringNode(this);
		_String_002.addInput(new armory.logicnode.StringNode(this, "Strahlteiler"), 0);
		_String_002.addOutputs([_SetProperty_004]);
		_SetProperty_004.addInput(_String_002, 0);
		_SetProperty_004.addOutputs([new armory.logicnode.NullNode(this)]);
		var _GetProperty_012 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_012 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_012.addOutputs([_GetProperty_012]);
		_GetProperty_012.addInput(_GlobalObject_012, 0);
		_GetProperty_012.addInput(new armory.logicnode.StringNode(this, "Subexercise"), 0);
		_GetProperty_012.addOutputs([new armory.logicnode.NullNode(this)]);
		_GetProperty_012.addOutputs([new armory.logicnode.StringNode(this, "")]);
		var _SetProperty_003 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_003.addInput(new armory.logicnode.NullNode(this), 0);
		var _GlobalObject_010 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_010.addOutputs([_SetProperty_003]);
		_SetProperty_003.addInput(_GlobalObject_010, 0);
		_SetProperty_003.addInput(new armory.logicnode.StringNode(this, "Exercise"), 0);
		var _String_001 = new armory.logicnode.StringNode(this);
		_String_001.addInput(new armory.logicnode.StringNode(this, "Vorversuch"), 0);
		_String_001.addOutputs([_SetProperty_003]);
		_SetProperty_003.addInput(_String_001, 0);
		_SetProperty_003.addOutputs([new armory.logicnode.NullNode(this)]);
		var _GetProperty_011 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_009 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_009.addOutputs([_GetProperty_011]);
		_GetProperty_011.addInput(_GlobalObject_009, 0);
		_GetProperty_011.addInput(new armory.logicnode.StringNode(this, "Exercise"), 0);
		_GetProperty_011.addOutputs([new armory.logicnode.NullNode(this)]);
		_GetProperty_011.addOutputs([new armory.logicnode.StringNode(this, "")]);
		var _CallFunction_001 = new armory.logicnode.CallFunctionNode(this);
		_CallFunction_001.addInput(new armory.logicnode.NullNode(this), 0);
		var _GetTrait_001 = new armory.logicnode.GetTraitNode(this);
		_GetTrait_001.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetTrait_001.addInput(new armory.logicnode.StringNode(this, "ServerInterface"), 0);
		_GetTrait_001.addOutputs([_CallFunction_001]);
		_CallFunction_001.addInput(_GetTrait_001, 0);
		_CallFunction_001.addInput(new armory.logicnode.StringNode(this, "saveTMP"), 0);
		_CallFunction_001.addOutputs([new armory.logicnode.NullNode(this)]);
		_CallFunction_001.addOutputs([new armory.logicnode.NullNode(this)]);
		var _CallFunction = new armory.logicnode.CallFunctionNode(this);
		_CallFunction.addInput(new armory.logicnode.NullNode(this), 0);
		var _GetTrait = new armory.logicnode.GetTraitNode(this);
		_GetTrait.addInput(new armory.logicnode.ObjectNode(this, ""), 0);
		_GetTrait.addInput(new armory.logicnode.StringNode(this, "ServerInterface"), 0);
		_GetTrait.addOutputs([_CallFunction]);
		_CallFunction.addInput(_GetTrait, 0);
		_CallFunction.addInput(new armory.logicnode.StringNode(this, "exportData"), 0);
		_CallFunction.addOutputs([new armory.logicnode.NullNode(this)]);
		_CallFunction.addOutputs([new armory.logicnode.NullNode(this)]);
		var _SetProperty_002 = new armory.logicnode.SetPropertyNode(this);
		_SetProperty_002.addInput(new armory.logicnode.NullNode(this), 0);
		var _GlobalObject_007 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_007.addOutputs([_SetProperty_002]);
		_SetProperty_002.addInput(_GlobalObject_007, 0);
		_SetProperty_002.addInput(new armory.logicnode.StringNode(this, "FileName"), 0);
		var _String = new armory.logicnode.StringNode(this);
		_String.addInput(new armory.logicnode.StringNode(this, "TestName"), 0);
		_String.addOutputs([_SetProperty_002]);
		_SetProperty_002.addInput(_String, 0);
		_SetProperty_002.addOutputs([new armory.logicnode.NullNode(this)]);
		var _GetProperty_010 = new armory.logicnode.GetPropertyNode(this);
		var _GlobalObject_008 = new armory.logicnode.GlobalObjectNode(this);
		_GlobalObject_008.addOutputs([_GetProperty_010]);
		_GetProperty_010.addInput(_GlobalObject_008, 0);
		_GetProperty_010.addInput(new armory.logicnode.StringNode(this, "FileName"), 0);
		_GetProperty_010.addOutputs([new armory.logicnode.NullNode(this)]);
		_GetProperty_010.addOutputs([new armory.logicnode.StringNode(this, "")]);
	}
}