# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MiReQuServerUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoincidenceStream(object):
    def setupUi(self, CoincidenceStream):
        CoincidenceStream.setObjectName("CoincidenceStream")
        CoincidenceStream.resize(181, 115)
        self.centralwidget = QtWidgets.QWidget(CoincidenceStream)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout.addWidget(self.stopButton)
        CoincidenceStream.setCentralWidget(self.centralwidget)

        self.retranslateUi(CoincidenceStream)
        QtCore.QMetaObject.connectSlotsByName(CoincidenceStream)

    def retranslateUi(self, CoincidenceStream):
        _translate = QtCore.QCoreApplication.translate
        CoincidenceStream.setWindowTitle(_translate("CoincidenceStream", "CoincidenceStream", None, -1))
        self.startButton.setText(_translate("CoincidenceStream", "Start", None, -1))
        self.stopButton.setText(_translate("CoincidenceStream", "Stop", None, -1))
